// defsgen generates the checked-in static world data in facts/ from the
// OpenRSC server tree, so a deployed host needs ZERO runtime file I/O and no
// openrsc checkout — "all the defs/locs should be hardcoded".
//
// Two layers, split by source format:
//
//   - Defs + locs (XML/JSON): loaded through the exact same facts.Load path
//     the runtime used to call, then re-emitted as Go literals — parity with
//     the legacy loader is by construction, and verified by
//     facts.TestStaticParity against a live tree.
//   - Name<->id symbol layer (constants/*.java): the Java enums have no
//     runtime parse path (no Java at host runtime), so they are extracted
//     here at build time. There are FIVE distinct shapes, not one regex:
//     enum NAME(int) for ItemId/NpcId/SceneryId/BoundaryId; static final int
//     for Quests/AppearanceSlots; a commented-out int map for Skills; an
//     ordinal enum for Spells.
//
// Run via: go generate ./facts  (or directly: go run ./cmd/defsgen)
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/gen0cide/westworld/facts"
)

func main() {
	root := flag.String("openrsc", defaultRoot(), "OpenRSC source tree root")
	out := flag.String("out", "facts", "output directory (the facts package)")
	flag.Parse()

	f, err := facts.Load(facts.DefaultSources(*root))
	if err != nil {
		fatal("load defs from %s: %v", *root, err)
	}

	writeGen(*out, "static_defs_gen.go", genDefs(f))
	writeGen(*out, "static_locs_gen.go", genLocs(f))
	writeGen(*out, "idnames_gen.go", genIDNames(filepath.Join(*root, "server", "src", "com", "openrsc", "server", "constants")))
	fmt.Println("defsgen: regenerated facts/static_defs_gen.go, static_locs_gen.go, idnames_gen.go")
}

func defaultRoot() string {
	if v := os.Getenv("OPENRSC_ROOT"); v != "" {
		return v
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, "Code", "openrsc")
}

func fatal(f string, args ...any) {
	fmt.Fprintf(os.Stderr, "defsgen: "+f+"\n", args...)
	os.Exit(1)
}

const header = `// Code generated by cmd/defsgen from the OpenRSC server tree. DO NOT EDIT.
// Regenerate with: go generate ./facts

package facts

`

func writeGen(dir, name, body string) {
	src := header + body
	formatted, err := format.Source([]byte(src))
	if err != nil {
		// Dump the unformatted source so the bug is debuggable.
		_ = os.WriteFile(filepath.Join(dir, name+".broken"), []byte(src), 0o644)
		fatal("gofmt %s: %v", name, err)
	}
	if err := os.WriteFile(filepath.Join(dir, name), formatted, 0o644); err != nil {
		fatal("write %s: %v", name, err)
	}
}

// ----- defs (field-named literals via %#v; shapes change, regen follows) -----

func genDefs(f *facts.Facts) string {
	var b strings.Builder

	emitMap := func(name, typ string, ids []int, get func(int) any) {
		fmt.Fprintf(&b, "var %s = map[int]*%s{\n", name, typ)
		for _, id := range ids {
			v := fmt.Sprintf("%#v", get(id))
			v = strings.TrimPrefix(v, "&")
			v = strings.ReplaceAll(v, "facts.", "")
			fmt.Fprintf(&b, "%d: &%s,\n", id, v)
		}
		b.WriteString("}\n\n")
	}

	emitMap("sceneryDefsGen", "SceneryDef", sortedKeys(f.SceneryDefs), func(id int) any { return f.SceneryDefs[id] })
	emitMap("boundaryDefsGen", "BoundaryDef", sortedKeys(f.BoundaryDefs), func(id int) any { return f.BoundaryDefs[id] })
	emitMap("npcDefsGen", "NpcDef", sortedKeys(f.NpcDefs), func(id int) any { return f.NpcDefs[id] })
	emitMap("itemDefsGen", "ItemDef", sortedKeys(f.ItemDefs), func(id int) any { return f.ItemDefs[id] })

	b.WriteString("var tileDefsGen = []TileDef{\n")
	for _, d := range f.TileDefs {
		v := strings.ReplaceAll(fmt.Sprintf("%#v", d), "facts.TileDef", "")
		fmt.Fprintf(&b, "%s,\n", v)
	}
	b.WriteString("}\n")
	return b.String()
}

func sortedKeys[V any](m map[int]V) []int {
	out := make([]int, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Ints(out)
	return out
}

// ----- locs (positional literals; tens of thousands of rows, all ints) -----

func genLocs(f *facts.Facts) string {
	var b strings.Builder

	b.WriteString("var sceneryLocsGen = []SceneryLoc{\n")
	for _, l := range f.SceneryLocs {
		fmt.Fprintf(&b, "{%d, %d, %d, %d},\n", l.DefID, l.X, l.Y, l.Direction)
	}
	b.WriteString("}\n\n")

	b.WriteString("var boundaryLocsGen = []BoundaryLoc{\n")
	for _, l := range f.BoundaryLocs {
		fmt.Fprintf(&b, "{%d, %d, %d, %d},\n", l.DefID, l.X, l.Y, l.Direction)
	}
	b.WriteString("}\n\n")

	b.WriteString("var npcLocsGen = []NpcLoc{\n")
	for _, l := range f.NpcLocs {
		fmt.Fprintf(&b, "{%d, %d, %d, %d, %d, %d, %d},\n", l.DefID, l.StartX, l.StartY, l.MinX, l.MinY, l.MaxX, l.MaxY)
	}
	b.WriteString("}\n\n")

	b.WriteString("var groundItemLocsGen = []GroundItemLoc{\n")
	for _, l := range f.GroundItemLocs {
		fmt.Fprintf(&b, "{%d, %d, %d, %d},\n", l.DefID, l.X, l.Y, l.RespawnMs)
	}
	b.WriteString("}\n")
	return b.String()
}

// ----- Java constants/*.java — the five parse shapes -----

func genIDNames(constDir string) string {
	var b strings.Builder
	b.WriteString(`// The name<->id symbol layer extracted from OpenRSC's constants/*.java —
// SNAKE_CASE authoring names (the same vocabulary the server source uses)
// resolving to wire ids. Java enums have no runtime parse path, hence
// build-time extraction.

`)
	emit := func(name string, pairs []idName) {
		fmt.Fprintf(&b, "var %s = map[string]int{\n", name)
		for _, p := range pairs {
			fmt.Fprintf(&b, "%q: %d,\n", p.name, p.id)
		}
		b.WriteString("}\n\n")
	}

	emit("ItemIDByName", dedupe("ItemId.java", parseEnumInt(stripComments(readConst(constDir, "ItemId.java")))))
	emit("NpcIDByName", dedupe("NpcId.java", parseEnumInt(stripComments(readConst(constDir, "NpcId.java")))))
	emit("SceneryIDByName", dedupe("SceneryId.java", parseEnumInt(stripComments(readConst(constDir, "SceneryId.java")))))
	emit("BoundaryIDByName", dedupe("BoundaryId.java", parseEnumInt(stripComments(readConst(constDir, "BoundaryId.java")))))
	emit("QuestIDByName", dedupe("Quests.java", parseStaticFinalInt(stripComments(readConst(constDir, "Quests.java")))))
	emit("AppearanceSlotByName", dedupe("AppearanceSlots.java", parseStaticFinalInt(stripComments(readConst(constDir, "AppearanceSlots.java")))))
	emit("SkillIDByName", dedupe("Skills.java", parseSkillsCommentedMap(readConst(constDir, "Skills.java"))))
	emit("SpellOrdinalByName", dedupe("Spells.java", parseOrdinalEnum(stripComments(readConst(constDir, "Spells.java")))))
	return b.String()
}

type idName struct {
	name string
	id   int
}

// stripComments removes /* */ and // comments — OpenRSC's enum files carry
// commented-out placeholder blocks (e.g. SceneryId's unnamed STONE_BRIDGE
// run) that must not reach the symbol table. Skills.java is deliberately
// parsed UN-stripped, since its int map only survives inside a comment.
var (
	blockCommentRe = regexp.MustCompile(`(?s)/\*.*?\*/`)
	lineCommentRe  = regexp.MustCompile(`//[^\n]*`)
)

func stripComments(src string) string {
	return lineCommentRe.ReplaceAllString(blockCommentRe.ReplaceAllString(src, ""), "")
}

// dedupe asserts the parsed table has no duplicate names — a duplicate after
// comment-stripping means a parser bug, not data.
func dedupe(file string, pairs []idName) []idName {
	seen := map[string]int{}
	for _, p := range pairs {
		if prev, ok := seen[p.name]; ok {
			fatal("%s: duplicate symbol %s (ids %d and %d)", file, p.name, prev, p.id)
		}
		seen[p.name] = p.id
	}
	return pairs
}

func readConst(dir, file string) string {
	b, err := os.ReadFile(filepath.Join(dir, file))
	if err != nil {
		fatal("read %s: %v", file, err)
	}
	return string(b)
}

// Shape 1: enum NAME(int) — ItemId/NpcId/SceneryId/BoundaryId.
var enumIntRe = regexp.MustCompile(`(?m)^\s*([A-Z][A-Z0-9_]*)\((-?\d+)\)\s*[,;]`)

func parseEnumInt(src string) []idName {
	var out []idName
	for _, m := range enumIntRe.FindAllStringSubmatch(src, -1) {
		id, _ := strconv.Atoi(m[2])
		out = append(out, idName{m[1], id})
	}
	if len(out) == 0 {
		fatal("enum NAME(int) parse found nothing")
	}
	return out
}

// Shape 2: [public] static final int NAME = N; — Quests/AppearanceSlots
// (handles comma-chained multi-declarations too).
var staticIntDeclRe = regexp.MustCompile(`(?ms)(?:public\s+)?static\s+final\s+int\s+(.*?);`)
var nameEqIntRe = regexp.MustCompile(`([A-Z][A-Z0-9_]*)\s*=\s*(-?\d+)`)

func parseStaticFinalInt(src string) []idName {
	var out []idName
	for _, decl := range staticIntDeclRe.FindAllStringSubmatch(src, -1) {
		for _, m := range nameEqIntRe.FindAllStringSubmatch(decl[1], -1) {
			id, _ := strconv.Atoi(m[2])
			out = append(out, idName{m[1], id})
		}
	}
	if len(out) == 0 {
		fatal("static final int parse found nothing")
	}
	return out
}

// Shape 3: Skills.java — the canonical int mapping survives only inside a
// block comment (`/*public static final int ATTACK = 0, ... PETRANGED = 23;*/`);
// the live class keys skills by string name. Extract NAME = N pairs from
// that commented block alone, so live `static final int` decls (e.g. combat
// stance modes) don't pollute the skill table.
func parseSkillsCommentedMap(src string) []idName {
	start := strings.Index(src, "/*public static final int ATTACK")
	if start < 0 {
		fatal("Skills.java: commented int map not found (format changed?)")
	}
	end := strings.Index(src[start:], "*/")
	if end < 0 {
		fatal("Skills.java: unterminated comment block")
	}
	block := src[start : start+end]
	var out []idName
	for _, m := range nameEqIntRe.FindAllStringSubmatch(block, -1) {
		id, _ := strconv.Atoi(m[2])
		out = append(out, idName{m[1], id})
	}
	if len(out) == 0 {
		fatal("Skills.java: no NAME = N pairs in the commented block")
	}
	return out
}

// Shape 4: ordinal enum — Spells.java; index = declaration position.
var enumBodyRe = regexp.MustCompile(`(?s)public\s+enum\s+\w+\s*\{(.*)\}`)
var bareIdentRe = regexp.MustCompile(`(?m)^\s*([A-Z][A-Z0-9_]*)\s*,?\s*(?://.*)?$`)

func parseOrdinalEnum(src string) []idName {
	body := enumBodyRe.FindStringSubmatch(src)
	if body == nil {
		fatal("ordinal enum body not found")
	}
	var out []idName
	for i, m := range bareIdentRe.FindAllStringSubmatch(body[1], -1) {
		out = append(out, idName{m[1], i})
	}
	if len(out) == 0 {
		fatal("ordinal enum parse found nothing")
	}
	return out
}
