// host ↔ mesa wire contract (v2, game-native). See docs/mesa/PROTOCOL.md for the
// prose. The host ships game SITUATIONS up and receives game MOVES (DSL) down;
// mesa owns LLM inference, RAG, long-term memory, and the persona lifecycle.
//
// Pure-proto3, no CGO: generated by buf with local protoc-gen-go(-grpc) plugins.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: mesa.proto

package mesapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Game_Act_FullMethodName    = "/westworld.mesa.v2.Game/Act"
	Game_Decide_FullMethodName = "/westworld.mesa.v2.Game/Decide"
	Game_Chat_FullMethodName   = "/westworld.mesa.v2.Game/Chat"
)

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ───────── Game — the agent interface (the core) ─────────
type GameClient interface {
	Act(ctx context.Context, in *Situation, opts ...grpc.CallOption) (*Move, error)
	Decide(ctx context.Context, in *Choice, opts ...grpc.CallOption) (*Decision, error)
	Chat(ctx context.Context, in *ChatTurn, opts ...grpc.CallOption) (*ChatReply, error)
}

type gameClient struct {
	cc grpc.ClientConnInterface
}

func NewGameClient(cc grpc.ClientConnInterface) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) Act(ctx context.Context, in *Situation, opts ...grpc.CallOption) (*Move, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Move)
	err := c.cc.Invoke(ctx, Game_Act_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) Decide(ctx context.Context, in *Choice, opts ...grpc.CallOption) (*Decision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Decision)
	err := c.cc.Invoke(ctx, Game_Decide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) Chat(ctx context.Context, in *ChatTurn, opts ...grpc.CallOption) (*ChatReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatReply)
	err := c.cc.Invoke(ctx, Game_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServer is the server API for Game service.
// All implementations must embed UnimplementedGameServer
// for forward compatibility.
//
// ───────── Game — the agent interface (the core) ─────────
type GameServer interface {
	Act(context.Context, *Situation) (*Move, error)
	Decide(context.Context, *Choice) (*Decision, error)
	Chat(context.Context, *ChatTurn) (*ChatReply, error)
	mustEmbedUnimplementedGameServer()
}

// UnimplementedGameServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServer struct{}

func (UnimplementedGameServer) Act(context.Context, *Situation) (*Move, error) {
	return nil, status.Error(codes.Unimplemented, "method Act not implemented")
}
func (UnimplementedGameServer) Decide(context.Context, *Choice) (*Decision, error) {
	return nil, status.Error(codes.Unimplemented, "method Decide not implemented")
}
func (UnimplementedGameServer) Chat(context.Context, *ChatTurn) (*ChatReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedGameServer) mustEmbedUnimplementedGameServer() {}
func (UnimplementedGameServer) testEmbeddedByValue()              {}

// UnsafeGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServer will
// result in compilation errors.
type UnsafeGameServer interface {
	mustEmbedUnimplementedGameServer()
}

func RegisterGameServer(s grpc.ServiceRegistrar, srv GameServer) {
	// If the following call panics, it indicates UnimplementedGameServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Game_ServiceDesc, srv)
}

func _Game_Act_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Situation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).Act(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_Act_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).Act(ctx, req.(*Situation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_Decide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Choice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).Decide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_Decide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).Decide(ctx, req.(*Choice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatTurn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).Chat(ctx, req.(*ChatTurn))
	}
	return interceptor(ctx, in, info, handler)
}

// Game_ServiceDesc is the grpc.ServiceDesc for Game service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Game_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "westworld.mesa.v2.Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Act",
			Handler:    _Game_Act_Handler,
		},
		{
			MethodName: "Decide",
			Handler:    _Game_Decide_Handler,
		},
		{
			MethodName: "Chat",
			Handler:    _Game_Chat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mesa.proto",
}

const (
	Knowledge_Recall_FullMethodName = "/westworld.mesa.v2.Knowledge/Recall"
)

// KnowledgeClient is the client API for Knowledge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ───────── Knowledge — game recall (RAG, game-typed) ─────────
type KnowledgeClient interface {
	Recall(ctx context.Context, in *Query, opts ...grpc.CallOption) (*KnowledgeSet, error)
}

type knowledgeClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeClient(cc grpc.ClientConnInterface) KnowledgeClient {
	return &knowledgeClient{cc}
}

func (c *knowledgeClient) Recall(ctx context.Context, in *Query, opts ...grpc.CallOption) (*KnowledgeSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeSet)
	err := c.cc.Invoke(ctx, Knowledge_Recall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeServer is the server API for Knowledge service.
// All implementations must embed UnimplementedKnowledgeServer
// for forward compatibility.
//
// ───────── Knowledge — game recall (RAG, game-typed) ─────────
type KnowledgeServer interface {
	Recall(context.Context, *Query) (*KnowledgeSet, error)
	mustEmbedUnimplementedKnowledgeServer()
}

// UnimplementedKnowledgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeServer struct{}

func (UnimplementedKnowledgeServer) Recall(context.Context, *Query) (*KnowledgeSet, error) {
	return nil, status.Error(codes.Unimplemented, "method Recall not implemented")
}
func (UnimplementedKnowledgeServer) mustEmbedUnimplementedKnowledgeServer() {}
func (UnimplementedKnowledgeServer) testEmbeddedByValue()                   {}

// UnsafeKnowledgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeServer will
// result in compilation errors.
type UnsafeKnowledgeServer interface {
	mustEmbedUnimplementedKnowledgeServer()
}

func RegisterKnowledgeServer(s grpc.ServiceRegistrar, srv KnowledgeServer) {
	// If the following call panics, it indicates UnimplementedKnowledgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Knowledge_ServiceDesc, srv)
}

func _Knowledge_Recall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServer).Recall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Knowledge_Recall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServer).Recall(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

// Knowledge_ServiceDesc is the grpc.ServiceDesc for Knowledge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Knowledge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "westworld.mesa.v2.Knowledge",
	HandlerType: (*KnowledgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recall",
			Handler:    _Knowledge_Recall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mesa.proto",
}

const (
	Journal_Remember_FullMethodName = "/westworld.mesa.v2.Journal/Remember"
)

// JournalClient is the client API for Journal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ───────── Journal — game memory write (Mirror; async) ─────────
type JournalClient interface {
	Remember(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Episode, RememberAck], error)
}

type journalClient struct {
	cc grpc.ClientConnInterface
}

func NewJournalClient(cc grpc.ClientConnInterface) JournalClient {
	return &journalClient{cc}
}

func (c *journalClient) Remember(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Episode, RememberAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Journal_ServiceDesc.Streams[0], Journal_Remember_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Episode, RememberAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Journal_RememberClient = grpc.ClientStreamingClient[Episode, RememberAck]

// JournalServer is the server API for Journal service.
// All implementations must embed UnimplementedJournalServer
// for forward compatibility.
//
// ───────── Journal — game memory write (Mirror; async) ─────────
type JournalServer interface {
	Remember(grpc.ClientStreamingServer[Episode, RememberAck]) error
	mustEmbedUnimplementedJournalServer()
}

// UnimplementedJournalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJournalServer struct{}

func (UnimplementedJournalServer) Remember(grpc.ClientStreamingServer[Episode, RememberAck]) error {
	return status.Error(codes.Unimplemented, "method Remember not implemented")
}
func (UnimplementedJournalServer) mustEmbedUnimplementedJournalServer() {}
func (UnimplementedJournalServer) testEmbeddedByValue()                 {}

// UnsafeJournalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JournalServer will
// result in compilation errors.
type UnsafeJournalServer interface {
	mustEmbedUnimplementedJournalServer()
}

func RegisterJournalServer(s grpc.ServiceRegistrar, srv JournalServer) {
	// If the following call panics, it indicates UnimplementedJournalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Journal_ServiceDesc, srv)
}

func _Journal_Remember_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JournalServer).Remember(&grpc.GenericServerStream[Episode, RememberAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Journal_RememberServer = grpc.ClientStreamingServer[Episode, RememberAck]

// Journal_ServiceDesc is the grpc.ServiceDesc for Journal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Journal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "westworld.mesa.v2.Journal",
	HandlerType: (*JournalServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Remember",
			Handler:       _Journal_Remember_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "mesa.proto",
}

const (
	Provision_Fetch_FullMethodName     = "/westworld.mesa.v2.Provision/Fetch"
	Provision_Subscribe_FullMethodName = "/westworld.mesa.v2.Provision/Subscribe"
)

// ProvisionClient is the client API for Provision service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ───────── Provision — compiled game behavior (two paths) ─────────
// Unary Fetch for initial/on-demand sync; server-stream Subscribe for live
// pushes (the "server-side eventing" path).
type ProvisionClient interface {
	Fetch(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*Provisioning, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Directive], error)
}

type provisionClient struct {
	cc grpc.ClientConnInterface
}

func NewProvisionClient(cc grpc.ClientConnInterface) ProvisionClient {
	return &provisionClient{cc}
}

func (c *provisionClient) Fetch(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*Provisioning, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Provisioning)
	err := c.cc.Invoke(ctx, Provision_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Directive], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Provision_ServiceDesc.Streams[0], Provision_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Directive]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provision_SubscribeClient = grpc.ServerStreamingClient[Directive]

// ProvisionServer is the server API for Provision service.
// All implementations must embed UnimplementedProvisionServer
// for forward compatibility.
//
// ───────── Provision — compiled game behavior (two paths) ─────────
// Unary Fetch for initial/on-demand sync; server-stream Subscribe for live
// pushes (the "server-side eventing" path).
type ProvisionServer interface {
	Fetch(context.Context, *HostRef) (*Provisioning, error)
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Directive]) error
	mustEmbedUnimplementedProvisionServer()
}

// UnimplementedProvisionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProvisionServer struct{}

func (UnimplementedProvisionServer) Fetch(context.Context, *HostRef) (*Provisioning, error) {
	return nil, status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedProvisionServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Directive]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedProvisionServer) mustEmbedUnimplementedProvisionServer() {}
func (UnimplementedProvisionServer) testEmbeddedByValue()                   {}

// UnsafeProvisionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvisionServer will
// result in compilation errors.
type UnsafeProvisionServer interface {
	mustEmbedUnimplementedProvisionServer()
}

func RegisterProvisionServer(s grpc.ServiceRegistrar, srv ProvisionServer) {
	// If the following call panics, it indicates UnimplementedProvisionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Provision_ServiceDesc, srv)
}

func _Provision_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provision_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServer).Fetch(ctx, req.(*HostRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provision_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProvisionServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Directive]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provision_SubscribeServer = grpc.ServerStreamingServer[Directive]

// Provision_ServiceDesc is the grpc.ServiceDesc for Provision service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Provision_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "westworld.mesa.v2.Provision",
	HandlerType: (*ProvisionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _Provision_Fetch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Provision_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mesa.proto",
}
