// host ↔ mesa wire contract (v2, game-native). See docs/mesa/PROTOCOL.md for the
// prose. The host ships game SITUATIONS up and receives game MOVES (DSL) down;
// mesa owns LLM inference, RAG, long-term memory, and the persona lifecycle.
//
// Pure-proto3, no CGO: generated by buf with local protoc-gen-go(-grpc) plugins.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: mesa.proto

package mesapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Game_Act_FullMethodName               = "/westworld.mesa.v2.Game/Act"
	Game_Decide_FullMethodName            = "/westworld.mesa.v2.Game/Decide"
	Game_Chat_FullMethodName              = "/westworld.mesa.v2.Game/Chat"
	Game_AnalysisInterpret_FullMethodName = "/westworld.mesa.v2.Game/AnalysisInterpret"
	Game_ExtractDialog_FullMethodName     = "/westworld.mesa.v2.Game/ExtractDialog"
)

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ───────── Game — the agent interface (the core) ─────────
type GameClient interface {
	Act(ctx context.Context, in *Situation, opts ...grpc.CallOption) (*Move, error)
	Decide(ctx context.Context, in *Choice, opts ...grpc.CallOption) (*Decision, error)
	Chat(ctx context.Context, in *ChatTurn, opts ...grpc.CallOption) (*ChatReply, error)
	AnalysisInterpret(ctx context.Context, in *AnalysisDirective, opts ...grpc.CallOption) (*AnalysisVerdict, error)
	ExtractDialog(ctx context.Context, in *DialogWindow, opts ...grpc.CallOption) (*ExtractedDialogSet, error)
}

type gameClient struct {
	cc grpc.ClientConnInterface
}

func NewGameClient(cc grpc.ClientConnInterface) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) Act(ctx context.Context, in *Situation, opts ...grpc.CallOption) (*Move, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Move)
	err := c.cc.Invoke(ctx, Game_Act_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) Decide(ctx context.Context, in *Choice, opts ...grpc.CallOption) (*Decision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Decision)
	err := c.cc.Invoke(ctx, Game_Decide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) Chat(ctx context.Context, in *ChatTurn, opts ...grpc.CallOption) (*ChatReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatReply)
	err := c.cc.Invoke(ctx, Game_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) AnalysisInterpret(ctx context.Context, in *AnalysisDirective, opts ...grpc.CallOption) (*AnalysisVerdict, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalysisVerdict)
	err := c.cc.Invoke(ctx, Game_AnalysisInterpret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) ExtractDialog(ctx context.Context, in *DialogWindow, opts ...grpc.CallOption) (*ExtractedDialogSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractedDialogSet)
	err := c.cc.Invoke(ctx, Game_ExtractDialog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServer is the server API for Game service.
// All implementations must embed UnimplementedGameServer
// for forward compatibility.
//
// ───────── Game — the agent interface (the core) ─────────
type GameServer interface {
	Act(context.Context, *Situation) (*Move, error)
	Decide(context.Context, *Choice) (*Decision, error)
	Chat(context.Context, *ChatTurn) (*ChatReply, error)
	AnalysisInterpret(context.Context, *AnalysisDirective) (*AnalysisVerdict, error)
	ExtractDialog(context.Context, *DialogWindow) (*ExtractedDialogSet, error)
	mustEmbedUnimplementedGameServer()
}

// UnimplementedGameServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServer struct{}

func (UnimplementedGameServer) Act(context.Context, *Situation) (*Move, error) {
	return nil, status.Error(codes.Unimplemented, "method Act not implemented")
}
func (UnimplementedGameServer) Decide(context.Context, *Choice) (*Decision, error) {
	return nil, status.Error(codes.Unimplemented, "method Decide not implemented")
}
func (UnimplementedGameServer) Chat(context.Context, *ChatTurn) (*ChatReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedGameServer) AnalysisInterpret(context.Context, *AnalysisDirective) (*AnalysisVerdict, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalysisInterpret not implemented")
}
func (UnimplementedGameServer) ExtractDialog(context.Context, *DialogWindow) (*ExtractedDialogSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractDialog not implemented")
}
func (UnimplementedGameServer) mustEmbedUnimplementedGameServer() {}
func (UnimplementedGameServer) testEmbeddedByValue()              {}

// UnsafeGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServer will
// result in compilation errors.
type UnsafeGameServer interface {
	mustEmbedUnimplementedGameServer()
}

func RegisterGameServer(s grpc.ServiceRegistrar, srv GameServer) {
	// If the following call panics, it indicates UnimplementedGameServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Game_ServiceDesc, srv)
}

func _Game_Act_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Situation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).Act(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_Act_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).Act(ctx, req.(*Situation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_Decide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Choice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).Decide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_Decide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).Decide(ctx, req.(*Choice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatTurn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).Chat(ctx, req.(*ChatTurn))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_AnalysisInterpret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisDirective)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).AnalysisInterpret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_AnalysisInterpret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).AnalysisInterpret(ctx, req.(*AnalysisDirective))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_ExtractDialog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DialogWindow)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).ExtractDialog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Game_ExtractDialog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).ExtractDialog(ctx, req.(*DialogWindow))
	}
	return interceptor(ctx, in, info, handler)
}

// Game_ServiceDesc is the grpc.ServiceDesc for Game service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Game_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "westworld.mesa.v2.Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Act",
			Handler:    _Game_Act_Handler,
		},
		{
			MethodName: "Decide",
			Handler:    _Game_Decide_Handler,
		},
		{
			MethodName: "Chat",
			Handler:    _Game_Chat_Handler,
		},
		{
			MethodName: "AnalysisInterpret",
			Handler:    _Game_AnalysisInterpret_Handler,
		},
		{
			MethodName: "ExtractDialog",
			Handler:    _Game_ExtractDialog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mesa.proto",
}

const (
	Knowledge_Recall_FullMethodName             = "/westworld.mesa.v2.Knowledge/Recall"
	Knowledge_FetchRelationships_FullMethodName = "/westworld.mesa.v2.Knowledge/FetchRelationships"
	Knowledge_FetchGoal_FullMethodName          = "/westworld.mesa.v2.Knowledge/FetchGoal"
)

// KnowledgeClient is the client API for Knowledge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ───────── Knowledge — game recall (RAG, game-typed) ─────────
type KnowledgeClient interface {
	Recall(ctx context.Context, in *Query, opts ...grpc.CallOption) (*KnowledgeSet, error)
	FetchRelationships(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*RelationshipSet, error)
	FetchGoal(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*Goal, error)
}

type knowledgeClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeClient(cc grpc.ClientConnInterface) KnowledgeClient {
	return &knowledgeClient{cc}
}

func (c *knowledgeClient) Recall(ctx context.Context, in *Query, opts ...grpc.CallOption) (*KnowledgeSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeSet)
	err := c.cc.Invoke(ctx, Knowledge_Recall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeClient) FetchRelationships(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*RelationshipSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelationshipSet)
	err := c.cc.Invoke(ctx, Knowledge_FetchRelationships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeClient) FetchGoal(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*Goal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Goal)
	err := c.cc.Invoke(ctx, Knowledge_FetchGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeServer is the server API for Knowledge service.
// All implementations must embed UnimplementedKnowledgeServer
// for forward compatibility.
//
// ───────── Knowledge — game recall (RAG, game-typed) ─────────
type KnowledgeServer interface {
	Recall(context.Context, *Query) (*KnowledgeSet, error)
	FetchRelationships(context.Context, *HostRef) (*RelationshipSet, error)
	FetchGoal(context.Context, *HostRef) (*Goal, error)
	mustEmbedUnimplementedKnowledgeServer()
}

// UnimplementedKnowledgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeServer struct{}

func (UnimplementedKnowledgeServer) Recall(context.Context, *Query) (*KnowledgeSet, error) {
	return nil, status.Error(codes.Unimplemented, "method Recall not implemented")
}
func (UnimplementedKnowledgeServer) FetchRelationships(context.Context, *HostRef) (*RelationshipSet, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchRelationships not implemented")
}
func (UnimplementedKnowledgeServer) FetchGoal(context.Context, *HostRef) (*Goal, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchGoal not implemented")
}
func (UnimplementedKnowledgeServer) mustEmbedUnimplementedKnowledgeServer() {}
func (UnimplementedKnowledgeServer) testEmbeddedByValue()                   {}

// UnsafeKnowledgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeServer will
// result in compilation errors.
type UnsafeKnowledgeServer interface {
	mustEmbedUnimplementedKnowledgeServer()
}

func RegisterKnowledgeServer(s grpc.ServiceRegistrar, srv KnowledgeServer) {
	// If the following call panics, it indicates UnimplementedKnowledgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Knowledge_ServiceDesc, srv)
}

func _Knowledge_Recall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServer).Recall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Knowledge_Recall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServer).Recall(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _Knowledge_FetchRelationships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServer).FetchRelationships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Knowledge_FetchRelationships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServer).FetchRelationships(ctx, req.(*HostRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Knowledge_FetchGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServer).FetchGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Knowledge_FetchGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServer).FetchGoal(ctx, req.(*HostRef))
	}
	return interceptor(ctx, in, info, handler)
}

// Knowledge_ServiceDesc is the grpc.ServiceDesc for Knowledge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Knowledge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "westworld.mesa.v2.Knowledge",
	HandlerType: (*KnowledgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recall",
			Handler:    _Knowledge_Recall_Handler,
		},
		{
			MethodName: "FetchRelationships",
			Handler:    _Knowledge_FetchRelationships_Handler,
		},
		{
			MethodName: "FetchGoal",
			Handler:    _Knowledge_FetchGoal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mesa.proto",
}

const (
	Journal_Remember_FullMethodName           = "/westworld.mesa.v2.Journal/Remember"
	Journal_RecordObservations_FullMethodName = "/westworld.mesa.v2.Journal/RecordObservations"
	Journal_SyncRelationships_FullMethodName  = "/westworld.mesa.v2.Journal/SyncRelationships"
	Journal_SyncGoal_FullMethodName           = "/westworld.mesa.v2.Journal/SyncGoal"
	Journal_ReportMetrics_FullMethodName      = "/westworld.mesa.v2.Journal/ReportMetrics"
)

// JournalClient is the client API for Journal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ───────── Journal — game memory write (Mirror; async) ─────────
type JournalClient interface {
	Remember(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Episode, RememberAck], error)
	RecordObservations(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Observation, RememberAck], error)
	SyncRelationships(ctx context.Context, in *RelationshipSet, opts ...grpc.CallOption) (*SyncAck, error)
	SyncGoal(ctx context.Context, in *Goal, opts ...grpc.CallOption) (*SyncAck, error)
	ReportMetrics(ctx context.Context, in *MetricsReport, opts ...grpc.CallOption) (*SyncAck, error)
}

type journalClient struct {
	cc grpc.ClientConnInterface
}

func NewJournalClient(cc grpc.ClientConnInterface) JournalClient {
	return &journalClient{cc}
}

func (c *journalClient) Remember(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Episode, RememberAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Journal_ServiceDesc.Streams[0], Journal_Remember_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Episode, RememberAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Journal_RememberClient = grpc.ClientStreamingClient[Episode, RememberAck]

func (c *journalClient) RecordObservations(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Observation, RememberAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Journal_ServiceDesc.Streams[1], Journal_RecordObservations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Observation, RememberAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Journal_RecordObservationsClient = grpc.ClientStreamingClient[Observation, RememberAck]

func (c *journalClient) SyncRelationships(ctx context.Context, in *RelationshipSet, opts ...grpc.CallOption) (*SyncAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncAck)
	err := c.cc.Invoke(ctx, Journal_SyncRelationships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journalClient) SyncGoal(ctx context.Context, in *Goal, opts ...grpc.CallOption) (*SyncAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncAck)
	err := c.cc.Invoke(ctx, Journal_SyncGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journalClient) ReportMetrics(ctx context.Context, in *MetricsReport, opts ...grpc.CallOption) (*SyncAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncAck)
	err := c.cc.Invoke(ctx, Journal_ReportMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JournalServer is the server API for Journal service.
// All implementations must embed UnimplementedJournalServer
// for forward compatibility.
//
// ───────── Journal — game memory write (Mirror; async) ─────────
type JournalServer interface {
	Remember(grpc.ClientStreamingServer[Episode, RememberAck]) error
	RecordObservations(grpc.ClientStreamingServer[Observation, RememberAck]) error
	SyncRelationships(context.Context, *RelationshipSet) (*SyncAck, error)
	SyncGoal(context.Context, *Goal) (*SyncAck, error)
	ReportMetrics(context.Context, *MetricsReport) (*SyncAck, error)
	mustEmbedUnimplementedJournalServer()
}

// UnimplementedJournalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJournalServer struct{}

func (UnimplementedJournalServer) Remember(grpc.ClientStreamingServer[Episode, RememberAck]) error {
	return status.Error(codes.Unimplemented, "method Remember not implemented")
}
func (UnimplementedJournalServer) RecordObservations(grpc.ClientStreamingServer[Observation, RememberAck]) error {
	return status.Error(codes.Unimplemented, "method RecordObservations not implemented")
}
func (UnimplementedJournalServer) SyncRelationships(context.Context, *RelationshipSet) (*SyncAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncRelationships not implemented")
}
func (UnimplementedJournalServer) SyncGoal(context.Context, *Goal) (*SyncAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncGoal not implemented")
}
func (UnimplementedJournalServer) ReportMetrics(context.Context, *MetricsReport) (*SyncAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportMetrics not implemented")
}
func (UnimplementedJournalServer) mustEmbedUnimplementedJournalServer() {}
func (UnimplementedJournalServer) testEmbeddedByValue()                 {}

// UnsafeJournalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JournalServer will
// result in compilation errors.
type UnsafeJournalServer interface {
	mustEmbedUnimplementedJournalServer()
}

func RegisterJournalServer(s grpc.ServiceRegistrar, srv JournalServer) {
	// If the following call panics, it indicates UnimplementedJournalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Journal_ServiceDesc, srv)
}

func _Journal_Remember_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JournalServer).Remember(&grpc.GenericServerStream[Episode, RememberAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Journal_RememberServer = grpc.ClientStreamingServer[Episode, RememberAck]

func _Journal_RecordObservations_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JournalServer).RecordObservations(&grpc.GenericServerStream[Observation, RememberAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Journal_RecordObservationsServer = grpc.ClientStreamingServer[Observation, RememberAck]

func _Journal_SyncRelationships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelationshipSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalServer).SyncRelationships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Journal_SyncRelationships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalServer).SyncRelationships(ctx, req.(*RelationshipSet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Journal_SyncGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Goal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalServer).SyncGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Journal_SyncGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalServer).SyncGoal(ctx, req.(*Goal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Journal_ReportMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalServer).ReportMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Journal_ReportMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalServer).ReportMetrics(ctx, req.(*MetricsReport))
	}
	return interceptor(ctx, in, info, handler)
}

// Journal_ServiceDesc is the grpc.ServiceDesc for Journal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Journal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "westworld.mesa.v2.Journal",
	HandlerType: (*JournalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncRelationships",
			Handler:    _Journal_SyncRelationships_Handler,
		},
		{
			MethodName: "SyncGoal",
			Handler:    _Journal_SyncGoal_Handler,
		},
		{
			MethodName: "ReportMetrics",
			Handler:    _Journal_ReportMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Remember",
			Handler:       _Journal_Remember_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RecordObservations",
			Handler:       _Journal_RecordObservations_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "mesa.proto",
}

const (
	KV_Put_FullMethodName    = "/westworld.mesa.v2.KV/Put"
	KV_Get_FullMethodName    = "/westworld.mesa.v2.KV/Get"
	KV_Delete_FullMethodName = "/westworld.mesa.v2.KV/Delete"
)

// KVClient is the client API for KV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ───────── KV — generic host state mirror (memory.Manager remote tier) ─────────
// The clean home for arbitrary durable host state (goal/objective, progress
// markers, scratch the host wants to survive) — replacing the old hack of
// shoehorning KV writes into "kv" episodes. Host-namespaced.
type KVClient interface {
	Put(ctx context.Context, in *KVPut, opts ...grpc.CallOption) (*KVAck, error)
	Get(ctx context.Context, in *KVKey, opts ...grpc.CallOption) (*KVValue, error)
	Delete(ctx context.Context, in *KVKey, opts ...grpc.CallOption) (*KVAck, error)
}

type kVClient struct {
	cc grpc.ClientConnInterface
}

func NewKVClient(cc grpc.ClientConnInterface) KVClient {
	return &kVClient{cc}
}

func (c *kVClient) Put(ctx context.Context, in *KVPut, opts ...grpc.CallOption) (*KVAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVAck)
	err := c.cc.Invoke(ctx, KV_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVClient) Get(ctx context.Context, in *KVKey, opts ...grpc.CallOption) (*KVValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVValue)
	err := c.cc.Invoke(ctx, KV_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVClient) Delete(ctx context.Context, in *KVKey, opts ...grpc.CallOption) (*KVAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVAck)
	err := c.cc.Invoke(ctx, KV_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVServer is the server API for KV service.
// All implementations must embed UnimplementedKVServer
// for forward compatibility.
//
// ───────── KV — generic host state mirror (memory.Manager remote tier) ─────────
// The clean home for arbitrary durable host state (goal/objective, progress
// markers, scratch the host wants to survive) — replacing the old hack of
// shoehorning KV writes into "kv" episodes. Host-namespaced.
type KVServer interface {
	Put(context.Context, *KVPut) (*KVAck, error)
	Get(context.Context, *KVKey) (*KVValue, error)
	Delete(context.Context, *KVKey) (*KVAck, error)
	mustEmbedUnimplementedKVServer()
}

// UnimplementedKVServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKVServer struct{}

func (UnimplementedKVServer) Put(context.Context, *KVPut) (*KVAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedKVServer) Get(context.Context, *KVKey) (*KVValue, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKVServer) Delete(context.Context, *KVKey) (*KVAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedKVServer) mustEmbedUnimplementedKVServer() {}
func (UnimplementedKVServer) testEmbeddedByValue()            {}

// UnsafeKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KVServer will
// result in compilation errors.
type UnsafeKVServer interface {
	mustEmbedUnimplementedKVServer()
}

func RegisterKVServer(s grpc.ServiceRegistrar, srv KVServer) {
	// If the following call panics, it indicates UnimplementedKVServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KV_ServiceDesc, srv)
}

func _KV_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVPut)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KV_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).Put(ctx, req.(*KVPut))
	}
	return interceptor(ctx, in, info, handler)
}

func _KV_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KV_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).Get(ctx, req.(*KVKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _KV_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KV_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServer).Delete(ctx, req.(*KVKey))
	}
	return interceptor(ctx, in, info, handler)
}

// KV_ServiceDesc is the grpc.ServiceDesc for KV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "westworld.mesa.v2.KV",
	HandlerType: (*KVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _KV_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _KV_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KV_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mesa.proto",
}

const (
	Provision_Fetch_FullMethodName     = "/westworld.mesa.v2.Provision/Fetch"
	Provision_Subscribe_FullMethodName = "/westworld.mesa.v2.Provision/Subscribe"
	Provision_Genesis_FullMethodName   = "/westworld.mesa.v2.Provision/Genesis"
)

// ProvisionClient is the client API for Provision service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ───────── Provision — compiled game behavior (two paths) ─────────
// Unary Fetch for initial/on-demand sync; server-stream Subscribe for live
// pushes (the "server-side eventing" path).
type ProvisionClient interface {
	Fetch(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*Provisioning, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Directive], error)
	Genesis(ctx context.Context, in *GenesisRequest, opts ...grpc.CallOption) (*GenesisResult, error)
}

type provisionClient struct {
	cc grpc.ClientConnInterface
}

func NewProvisionClient(cc grpc.ClientConnInterface) ProvisionClient {
	return &provisionClient{cc}
}

func (c *provisionClient) Fetch(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*Provisioning, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Provisioning)
	err := c.cc.Invoke(ctx, Provision_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Directive], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Provision_ServiceDesc.Streams[0], Provision_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Directive]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provision_SubscribeClient = grpc.ServerStreamingClient[Directive]

func (c *provisionClient) Genesis(ctx context.Context, in *GenesisRequest, opts ...grpc.CallOption) (*GenesisResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenesisResult)
	err := c.cc.Invoke(ctx, Provision_Genesis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvisionServer is the server API for Provision service.
// All implementations must embed UnimplementedProvisionServer
// for forward compatibility.
//
// ───────── Provision — compiled game behavior (two paths) ─────────
// Unary Fetch for initial/on-demand sync; server-stream Subscribe for live
// pushes (the "server-side eventing" path).
type ProvisionServer interface {
	Fetch(context.Context, *HostRef) (*Provisioning, error)
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Directive]) error
	Genesis(context.Context, *GenesisRequest) (*GenesisResult, error)
	mustEmbedUnimplementedProvisionServer()
}

// UnimplementedProvisionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProvisionServer struct{}

func (UnimplementedProvisionServer) Fetch(context.Context, *HostRef) (*Provisioning, error) {
	return nil, status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedProvisionServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Directive]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedProvisionServer) Genesis(context.Context, *GenesisRequest) (*GenesisResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Genesis not implemented")
}
func (UnimplementedProvisionServer) mustEmbedUnimplementedProvisionServer() {}
func (UnimplementedProvisionServer) testEmbeddedByValue()                   {}

// UnsafeProvisionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvisionServer will
// result in compilation errors.
type UnsafeProvisionServer interface {
	mustEmbedUnimplementedProvisionServer()
}

func RegisterProvisionServer(s grpc.ServiceRegistrar, srv ProvisionServer) {
	// If the following call panics, it indicates UnimplementedProvisionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Provision_ServiceDesc, srv)
}

func _Provision_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provision_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServer).Fetch(ctx, req.(*HostRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provision_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProvisionServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Directive]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provision_SubscribeServer = grpc.ServerStreamingServer[Directive]

func _Provision_Genesis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenesisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServer).Genesis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provision_Genesis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServer).Genesis(ctx, req.(*GenesisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Provision_ServiceDesc is the grpc.ServiceDesc for Provision service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Provision_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "westworld.mesa.v2.Provision",
	HandlerType: (*ProvisionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _Provision_Fetch_Handler,
		},
		{
			MethodName: "Genesis",
			Handler:    _Provision_Genesis_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Provision_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mesa.proto",
}

const (
	Admin_PutPersonas_FullMethodName   = "/westworld.mesa.v2.Admin/PutPersonas"
	Admin_GetPersona_FullMethodName    = "/westworld.mesa.v2.Admin/GetPersona"
	Admin_ListPersonas_FullMethodName  = "/westworld.mesa.v2.Admin/ListPersonas"
	Admin_DeletePersona_FullMethodName = "/westworld.mesa.v2.Admin/DeletePersona"
	Admin_PushGoal_FullMethodName      = "/westworld.mesa.v2.Admin/PushGoal"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ───────── Admin — operator control plane (mesa-ctl) ─────────
// Operator-only: gated on the admin credential (ADMIN_TOKEN), NOT host tokens —
// a host must never rewrite another host's identity. Manages the persona
// registry at runtime, single or bulk, with no mesad restart: handlers reuse
// Server.Register (validate → render → persist to Postgres → register live).
type AdminClient interface {
	// PutPersonas bulk-upserts: the client streams personas, the server validates +
	// registers each, and returns a per-item report. One bad persona does NOT fail
	// the batch. A single put is just a stream of one.
	PutPersonas(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PersonaUpsert, BatchResult], error)
	GetPersona(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*PersonaRecord, error)
	ListPersonas(ctx context.Context, in *ListPersonasRequest, opts ...grpc.CallOption) (*PersonaList, error)
	DeletePersona(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*AdminAck, error)
	// PushGoal sets a SOFT runtime goal override on the matching, currently-running
	// hosts via the Provision.Subscribe push stream — no restart, no recompile. The
	// director prefers it over its genesis/persona goal until replaced. match is an
	// optional host_id glob (filepath.Match); empty matches every registered host.
	PushGoal(ctx context.Context, in *PushGoalRequest, opts ...grpc.CallOption) (*PushGoalResult, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) PutPersonas(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PersonaUpsert, BatchResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Admin_ServiceDesc.Streams[0], Admin_PutPersonas_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PersonaUpsert, BatchResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Admin_PutPersonasClient = grpc.ClientStreamingClient[PersonaUpsert, BatchResult]

func (c *adminClient) GetPersona(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*PersonaRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersonaRecord)
	err := c.cc.Invoke(ctx, Admin_GetPersona_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListPersonas(ctx context.Context, in *ListPersonasRequest, opts ...grpc.CallOption) (*PersonaList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersonaList)
	err := c.cc.Invoke(ctx, Admin_ListPersonas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeletePersona(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*AdminAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAck)
	err := c.cc.Invoke(ctx, Admin_DeletePersona_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) PushGoal(ctx context.Context, in *PushGoalRequest, opts ...grpc.CallOption) (*PushGoalResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushGoalResult)
	err := c.cc.Invoke(ctx, Admin_PushGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility.
//
// ───────── Admin — operator control plane (mesa-ctl) ─────────
// Operator-only: gated on the admin credential (ADMIN_TOKEN), NOT host tokens —
// a host must never rewrite another host's identity. Manages the persona
// registry at runtime, single or bulk, with no mesad restart: handlers reuse
// Server.Register (validate → render → persist to Postgres → register live).
type AdminServer interface {
	// PutPersonas bulk-upserts: the client streams personas, the server validates +
	// registers each, and returns a per-item report. One bad persona does NOT fail
	// the batch. A single put is just a stream of one.
	PutPersonas(grpc.ClientStreamingServer[PersonaUpsert, BatchResult]) error
	GetPersona(context.Context, *HostRef) (*PersonaRecord, error)
	ListPersonas(context.Context, *ListPersonasRequest) (*PersonaList, error)
	DeletePersona(context.Context, *HostRef) (*AdminAck, error)
	// PushGoal sets a SOFT runtime goal override on the matching, currently-running
	// hosts via the Provision.Subscribe push stream — no restart, no recompile. The
	// director prefers it over its genesis/persona goal until replaced. match is an
	// optional host_id glob (filepath.Match); empty matches every registered host.
	PushGoal(context.Context, *PushGoalRequest) (*PushGoalResult, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServer struct{}

func (UnimplementedAdminServer) PutPersonas(grpc.ClientStreamingServer[PersonaUpsert, BatchResult]) error {
	return status.Error(codes.Unimplemented, "method PutPersonas not implemented")
}
func (UnimplementedAdminServer) GetPersona(context.Context, *HostRef) (*PersonaRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPersona not implemented")
}
func (UnimplementedAdminServer) ListPersonas(context.Context, *ListPersonasRequest) (*PersonaList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPersonas not implemented")
}
func (UnimplementedAdminServer) DeletePersona(context.Context, *HostRef) (*AdminAck, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePersona not implemented")
}
func (UnimplementedAdminServer) PushGoal(context.Context, *PushGoalRequest) (*PushGoalResult, error) {
	return nil, status.Error(codes.Unimplemented, "method PushGoal not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}
func (UnimplementedAdminServer) testEmbeddedByValue()               {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	// If the following call panics, it indicates UnimplementedAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_PutPersonas_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdminServer).PutPersonas(&grpc.GenericServerStream[PersonaUpsert, BatchResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Admin_PutPersonasServer = grpc.ClientStreamingServer[PersonaUpsert, BatchResult]

func _Admin_GetPersona_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetPersona(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetPersona_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetPersona(ctx, req.(*HostRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListPersonas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPersonasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListPersonas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListPersonas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListPersonas(ctx, req.(*ListPersonasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeletePersona_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeletePersona(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_DeletePersona_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeletePersona(ctx, req.(*HostRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_PushGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).PushGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_PushGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).PushGoal(ctx, req.(*PushGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "westworld.mesa.v2.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPersona",
			Handler:    _Admin_GetPersona_Handler,
		},
		{
			MethodName: "ListPersonas",
			Handler:    _Admin_ListPersonas_Handler,
		},
		{
			MethodName: "DeletePersona",
			Handler:    _Admin_DeletePersona_Handler,
		},
		{
			MethodName: "PushGoal",
			Handler:    _Admin_PushGoal_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutPersonas",
			Handler:       _Admin_PutPersonas_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "mesa.proto",
}
