// host ↔ mesa wire contract (v2, game-native). See docs/mesa/PROTOCOL.md for the
// prose. The host ships game SITUATIONS up and receives game MOVES (DSL) down;
// mesa owns LLM inference, RAG, long-term memory, and the persona lifecycle.
//
// Pure-proto3, no CGO: generated by buf with local protoc-gen-go(-grpc) plugins.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mesa.proto

package mesapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveKind int32

const (
	MoveKind_RUN_ROUTINE   MoveKind = 0
	MoveKind_WRITE_ROUTINE MoveKind = 1
	MoveKind_DIRECT_ACTION MoveKind = 2
	MoveKind_IDLE          MoveKind = 3
)

// Enum value maps for MoveKind.
var (
	MoveKind_name = map[int32]string{
		0: "RUN_ROUTINE",
		1: "WRITE_ROUTINE",
		2: "DIRECT_ACTION",
		3: "IDLE",
	}
	MoveKind_value = map[string]int32{
		"RUN_ROUTINE":   0,
		"WRITE_ROUTINE": 1,
		"DIRECT_ACTION": 2,
		"IDLE":          3,
	}
)

func (x MoveKind) Enum() *MoveKind {
	p := new(MoveKind)
	*p = x
	return p
}

func (x MoveKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MoveKind) Descriptor() protoreflect.EnumDescriptor {
	return file_mesa_proto_enumTypes[0].Descriptor()
}

func (MoveKind) Type() protoreflect.EnumType {
	return &file_mesa_proto_enumTypes[0]
}

func (x MoveKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MoveKind.Descriptor instead.
func (MoveKind) EnumDescriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{0}
}

type QueryKind int32

const (
	QueryKind_ANY        QueryKind = 0
	QueryKind_PROCEDURAL QueryKind = 1
	QueryKind_ENTITY     QueryKind = 2
	QueryKind_EPISODIC   QueryKind = 3
	QueryKind_SOCIAL     QueryKind = 4
)

// Enum value maps for QueryKind.
var (
	QueryKind_name = map[int32]string{
		0: "ANY",
		1: "PROCEDURAL",
		2: "ENTITY",
		3: "EPISODIC",
		4: "SOCIAL",
	}
	QueryKind_value = map[string]int32{
		"ANY":        0,
		"PROCEDURAL": 1,
		"ENTITY":     2,
		"EPISODIC":   3,
		"SOCIAL":     4,
	}
)

func (x QueryKind) Enum() *QueryKind {
	p := new(QueryKind)
	*p = x
	return p
}

func (x QueryKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryKind) Descriptor() protoreflect.EnumDescriptor {
	return file_mesa_proto_enumTypes[1].Descriptor()
}

func (QueryKind) Type() protoreflect.EnumType {
	return &file_mesa_proto_enumTypes[1]
}

func (x QueryKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryKind.Descriptor instead.
func (QueryKind) EnumDescriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{1}
}

type DirectiveKind int32

const (
	DirectiveKind_DIRECTIVE_UNSPECIFIED DirectiveKind = 0
	DirectiveKind_ROUTINE_UPSERT        DirectiveKind = 1 // payload = a DSL routine for the library
	DirectiveKind_PEARL_REFRESH         DirectiveKind = 2 // payload = a persona Cornerstone to recompile from
	DirectiveKind_PERSONA_REVISION      DirectiveKind = 3 // payload = compiled Cornerstone
	DirectiveKind_GOAL_REVISION         DirectiveKind = 4
	DirectiveKind_TRUST_DECAY           DirectiveKind = 5
	DirectiveKind_REVERIE_REBASELINE    DirectiveKind = 6
)

// Enum value maps for DirectiveKind.
var (
	DirectiveKind_name = map[int32]string{
		0: "DIRECTIVE_UNSPECIFIED",
		1: "ROUTINE_UPSERT",
		2: "PEARL_REFRESH",
		3: "PERSONA_REVISION",
		4: "GOAL_REVISION",
		5: "TRUST_DECAY",
		6: "REVERIE_REBASELINE",
	}
	DirectiveKind_value = map[string]int32{
		"DIRECTIVE_UNSPECIFIED": 0,
		"ROUTINE_UPSERT":        1,
		"PEARL_REFRESH":         2,
		"PERSONA_REVISION":      3,
		"GOAL_REVISION":         4,
		"TRUST_DECAY":           5,
		"REVERIE_REBASELINE":    6,
	}
)

func (x DirectiveKind) Enum() *DirectiveKind {
	p := new(DirectiveKind)
	*p = x
	return p
}

func (x DirectiveKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DirectiveKind) Descriptor() protoreflect.EnumDescriptor {
	return file_mesa_proto_enumTypes[2].Descriptor()
}

func (DirectiveKind) Type() protoreflect.EnumType {
	return &file_mesa_proto_enumTypes[2]
}

func (x DirectiveKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DirectiveKind.Descriptor instead.
func (DirectiveKind) EnumDescriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{2}
}

type HostRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostId         string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	PersonaVersion string                 `protobuf:"bytes,2,opt,name=persona_version,json=personaVersion,proto3" json:"persona_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HostRef) Reset() {
	*x = HostRef{}
	mi := &file_mesa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostRef) ProtoMessage() {}

func (x *HostRef) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostRef.ProtoReflect.Descriptor instead.
func (*HostRef) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{0}
}

func (x *HostRef) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HostRef) GetPersonaVersion() string {
	if x != nil {
		return x.PersonaVersion
	}
	return ""
}

type Affect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stress        float64                `protobuf:"fixed64,1,opt,name=stress,proto3" json:"stress,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Valence       float64                `protobuf:"fixed64,3,opt,name=valence,proto3" json:"valence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Affect) Reset() {
	*x = Affect{}
	mi := &file_mesa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Affect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Affect) ProtoMessage() {}

func (x *Affect) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Affect.ProtoReflect.Descriptor instead.
func (*Affect) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{1}
}

func (x *Affect) GetStress() float64 {
	if x != nil {
		return x.Stress
	}
	return 0
}

func (x *Affect) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Affect) GetValence() float64 {
	if x != nil {
		return x.Valence
	}
	return 0
}

// ChatTurn is a player's utterance the host may reply to. Handled on a cheap
// model, out-of-band from Act, so chatting doesn't cost a full routine rewrite.
type ChatTurn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *HostRef               `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`       // the speaking player's name
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // what they said
	Recent        []string               `protobuf:"bytes,4,rep,name=recent,proto3" json:"recent,omitempty"`   // recent chat context (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatTurn) Reset() {
	*x = ChatTurn{}
	mi := &file_mesa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatTurn) ProtoMessage() {}

func (x *ChatTurn) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatTurn.ProtoReflect.Descriptor instead.
func (*ChatTurn) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{2}
}

func (x *ChatTurn) GetHost() *HostRef {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *ChatTurn) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ChatTurn) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatTurn) GetRecent() []string {
	if x != nil {
		return x.Recent
	}
	return nil
}

// ChatReply is the host's spoken reply. speak=false means stay silent.
type ChatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Speak         bool                   `protobuf:"varint,2,opt,name=speak,proto3" json:"speak,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReply) Reset() {
	*x = ChatReply{}
	mi := &file_mesa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReply) ProtoMessage() {}

func (x *ChatReply) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReply.ProtoReflect.Descriptor instead.
func (*ChatReply) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{3}
}

func (x *ChatReply) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatReply) GetSpeak() bool {
	if x != nil {
		return x.Speak
	}
	return false
}

type Situation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *HostRef               `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Goal          string                 `protobuf:"bytes,2,opt,name=goal,proto3" json:"goal,omitempty"`
	Trigger       string                 `protobuf:"bytes,3,opt,name=trigger,proto3" json:"trigger,omitempty"` // routine_exhausted | novel | chat | low_hp | ...
	World         *World                 `protobuf:"bytes,4,opt,name=world,proto3" json:"world,omitempty"`
	Recent        []string               `protobuf:"bytes,5,rep,name=recent,proto3" json:"recent,omitempty"`
	Affect        *Affect                `protobuf:"bytes,6,opt,name=affect,proto3" json:"affect,omitempty"`
	Hints         map[string]string      `protobuf:"bytes,7,rep,name=hints,proto3" json:"hints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Situation) Reset() {
	*x = Situation{}
	mi := &file_mesa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Situation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Situation) ProtoMessage() {}

func (x *Situation) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Situation.ProtoReflect.Descriptor instead.
func (*Situation) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{4}
}

func (x *Situation) GetHost() *HostRef {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Situation) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *Situation) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *Situation) GetWorld() *World {
	if x != nil {
		return x.World
	}
	return nil
}

func (x *Situation) GetRecent() []string {
	if x != nil {
		return x.Recent
	}
	return nil
}

func (x *Situation) GetAffect() *Affect {
	if x != nil {
		return x.Affect
	}
	return nil
}

func (x *Situation) GetHints() map[string]string {
	if x != nil {
		return x.Hints
	}
	return nil
}

type World struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	HpCur         int32                  `protobuf:"varint,4,opt,name=hp_cur,json=hpCur,proto3" json:"hp_cur,omitempty"`
	HpMax         int32                  `protobuf:"varint,5,opt,name=hp_max,json=hpMax,proto3" json:"hp_max,omitempty"`
	CombatLevel   int32                  `protobuf:"varint,6,opt,name=combat_level,json=combatLevel,proto3" json:"combat_level,omitempty"`
	Fatigue       float64                `protobuf:"fixed64,7,opt,name=fatigue,proto3" json:"fatigue,omitempty"`
	InvFree       int32                  `protobuf:"varint,8,opt,name=inv_free,json=invFree,proto3" json:"inv_free,omitempty"`
	InvSummary    []string               `protobuf:"bytes,9,rep,name=inv_summary,json=invSummary,proto3" json:"inv_summary,omitempty"`
	NearbyNpcs    []string               `protobuf:"bytes,10,rep,name=nearby_npcs,json=nearbyNpcs,proto3" json:"nearby_npcs,omitempty"`
	NearbyPlayers []string               `protobuf:"bytes,11,rep,name=nearby_players,json=nearbyPlayers,proto3" json:"nearby_players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *World) Reset() {
	*x = World{}
	mi := &file_mesa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *World) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*World) ProtoMessage() {}

func (x *World) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use World.ProtoReflect.Descriptor instead.
func (*World) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{5}
}

func (x *World) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *World) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *World) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *World) GetHpCur() int32 {
	if x != nil {
		return x.HpCur
	}
	return 0
}

func (x *World) GetHpMax() int32 {
	if x != nil {
		return x.HpMax
	}
	return 0
}

func (x *World) GetCombatLevel() int32 {
	if x != nil {
		return x.CombatLevel
	}
	return 0
}

func (x *World) GetFatigue() float64 {
	if x != nil {
		return x.Fatigue
	}
	return 0
}

func (x *World) GetInvFree() int32 {
	if x != nil {
		return x.InvFree
	}
	return 0
}

func (x *World) GetInvSummary() []string {
	if x != nil {
		return x.InvSummary
	}
	return nil
}

func (x *World) GetNearbyNpcs() []string {
	if x != nil {
		return x.NearbyNpcs
	}
	return nil
}

func (x *World) GetNearbyPlayers() []string {
	if x != nil {
		return x.NearbyPlayers
	}
	return nil
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          MoveKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=westworld.mesa.v2.MoveKind" json:"kind,omitempty"`
	Reasoning     string                 `protobuf:"bytes,2,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	RoutinePath   string                 `protobuf:"bytes,3,opt,name=routine_path,json=routinePath,proto3" json:"routine_path,omitempty"` // RUN_ROUTINE: a library routine
	RoutineName   string                 `protobuf:"bytes,4,opt,name=routine_name,json=routineName,proto3" json:"routine_name,omitempty"` // WRITE_ROUTINE: name of the authored routine
	DslSource     string                 `protobuf:"bytes,5,opt,name=dsl_source,json=dslSource,proto3" json:"dsl_source,omitempty"`       // WRITE_ROUTINE: the authored DSL (host parses+gates+runs)
	Quarantined   bool                   `protobuf:"varint,6,opt,name=quarantined,proto3" json:"quarantined,omitempty"`                   // WRITE_ROUTINE: run once/gated; do NOT auto-promote
	Args          []string               `protobuf:"bytes,7,rep,name=args,proto3" json:"args,omitempty"`                                  // RUN/WRITE routine args
	Verb          string                 `protobuf:"bytes,8,opt,name=verb,proto3" json:"verb,omitempty"`                                  // DIRECT_ACTION: a DSL action name
	ActionArgs    []string               `protobuf:"bytes,9,rep,name=action_args,json=actionArgs,proto3" json:"action_args,omitempty"`
	IdleSeconds   int32                  `protobuf:"varint,10,opt,name=idle_seconds,json=idleSeconds,proto3" json:"idle_seconds,omitempty"` // IDLE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_mesa_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{6}
}

func (x *Move) GetKind() MoveKind {
	if x != nil {
		return x.Kind
	}
	return MoveKind_RUN_ROUTINE
}

func (x *Move) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *Move) GetRoutinePath() string {
	if x != nil {
		return x.RoutinePath
	}
	return ""
}

func (x *Move) GetRoutineName() string {
	if x != nil {
		return x.RoutineName
	}
	return ""
}

func (x *Move) GetDslSource() string {
	if x != nil {
		return x.DslSource
	}
	return ""
}

func (x *Move) GetQuarantined() bool {
	if x != nil {
		return x.Quarantined
	}
	return false
}

func (x *Move) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Move) GetVerb() string {
	if x != nil {
		return x.Verb
	}
	return ""
}

func (x *Move) GetActionArgs() []string {
	if x != nil {
		return x.ActionArgs
	}
	return nil
}

func (x *Move) GetIdleSeconds() int32 {
	if x != nil {
		return x.IdleSeconds
	}
	return 0
}

type Choice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *HostRef               `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	Affect        *Affect                `protobuf:"bytes,4,opt,name=affect,proto3" json:"affect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_mesa_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{7}
}

func (x *Choice) GetHost() *HostRef {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Choice) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Choice) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Choice) GetAffect() *Affect {
	if x != nil {
		return x.Affect
	}
	return nil
}

type Decision struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Choice          string                 `protobuf:"bytes,1,opt,name=choice,proto3" json:"choice,omitempty"`
	Reasoning       string                 `protobuf:"bytes,2,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Confidence      float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	CacheKey        string                 `protobuf:"bytes,4,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	CacheTtlSeconds int64                  `protobuf:"varint,5,opt,name=cache_ttl_seconds,json=cacheTtlSeconds,proto3" json:"cache_ttl_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_mesa_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{8}
}

func (x *Decision) GetChoice() string {
	if x != nil {
		return x.Choice
	}
	return ""
}

func (x *Decision) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *Decision) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Decision) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *Decision) GetCacheTtlSeconds() int64 {
	if x != nil {
		return x.CacheTtlSeconds
	}
	return 0
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *HostRef               `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Kind          QueryKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=westworld.mesa.v2.QueryKind" json:"kind,omitempty"`
	TopK          int32                  `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_mesa_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{9}
}

func (x *Query) GetHost() *HostRef {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Query) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Query) GetKind() QueryKind {
	if x != nil {
		return x.Kind
	}
	return QueryKind_ANY
}

func (x *Query) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type KnowledgeSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KnowledgeItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeSet) Reset() {
	*x = KnowledgeSet{}
	mi := &file_mesa_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeSet) ProtoMessage() {}

func (x *KnowledgeSet) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeSet.ProtoReflect.Descriptor instead.
func (*KnowledgeSet) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{10}
}

func (x *KnowledgeSet) GetItems() []*KnowledgeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type KnowledgeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          QueryKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=westworld.mesa.v2.QueryKind" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Dsl           string                 `protobuf:"bytes,3,opt,name=dsl,proto3" json:"dsl,omitempty"` // set for procedural how-to
	Provenance    string                 `protobuf:"bytes,4,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeItem) Reset() {
	*x = KnowledgeItem{}
	mi := &file_mesa_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeItem) ProtoMessage() {}

func (x *KnowledgeItem) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeItem.ProtoReflect.Descriptor instead.
func (*KnowledgeItem) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{11}
}

func (x *KnowledgeItem) GetKind() QueryKind {
	if x != nil {
		return x.Kind
	}
	return QueryKind_ANY
}

func (x *KnowledgeItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *KnowledgeItem) GetDsl() string {
	if x != nil {
		return x.Dsl
	}
	return ""
}

func (x *KnowledgeItem) GetProvenance() string {
	if x != nil {
		return x.Provenance
	}
	return ""
}

func (x *KnowledgeItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Episode struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Host           *HostRef               `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // host_id + event-hash + occurred_at (UNIQUE)
	Kind           string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`                                           // kill|death|trade|scam|quest_step|discovery|social|kv
	Text           string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Importance     float64                `protobuf:"fixed64,5,opt,name=importance,proto3" json:"importance,omitempty"`
	OccurredAtUnix int64                  `protobuf:"varint,6,opt,name=occurred_at_unix,json=occurredAtUnix,proto3" json:"occurred_at_unix,omitempty"`
	Relation       *RelationDelta         `protobuf:"bytes,7,opt,name=relation,proto3" json:"relation,omitempty"`
	Tags           map[string]string      `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Episode) Reset() {
	*x = Episode{}
	mi := &file_mesa_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Episode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Episode) ProtoMessage() {}

func (x *Episode) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Episode.ProtoReflect.Descriptor instead.
func (*Episode) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{12}
}

func (x *Episode) GetHost() *HostRef {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Episode) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Episode) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Episode) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Episode) GetImportance() float64 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *Episode) GetOccurredAtUnix() int64 {
	if x != nil {
		return x.OccurredAtUnix
	}
	return 0
}

func (x *Episode) GetRelation() *RelationDelta {
	if x != nil {
		return x.Relation
	}
	return nil
}

func (x *Episode) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RelationDelta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DAlpha           float64                `protobuf:"fixed64,2,opt,name=d_alpha,json=dAlpha,proto3" json:"d_alpha,omitempty"`
	DBeta            float64                `protobuf:"fixed64,3,opt,name=d_beta,json=dBeta,proto3" json:"d_beta,omitempty"`
	DEncounters      int32                  `protobuf:"varint,4,opt,name=d_encounters,json=dEncounters,proto3" json:"d_encounters,omitempty"`
	TotalValueTraded float64                `protobuf:"fixed64,5,opt,name=total_value_traded,json=totalValueTraded,proto3" json:"total_value_traded,omitempty"`
	AddTags          []string               `protobuf:"bytes,6,rep,name=add_tags,json=addTags,proto3" json:"add_tags,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RelationDelta) Reset() {
	*x = RelationDelta{}
	mi := &file_mesa_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationDelta) ProtoMessage() {}

func (x *RelationDelta) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationDelta.ProtoReflect.Descriptor instead.
func (*RelationDelta) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{13}
}

func (x *RelationDelta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RelationDelta) GetDAlpha() float64 {
	if x != nil {
		return x.DAlpha
	}
	return 0
}

func (x *RelationDelta) GetDBeta() float64 {
	if x != nil {
		return x.DBeta
	}
	return 0
}

func (x *RelationDelta) GetDEncounters() int32 {
	if x != nil {
		return x.DEncounters
	}
	return 0
}

func (x *RelationDelta) GetTotalValueTraded() float64 {
	if x != nil {
		return x.TotalValueTraded
	}
	return 0
}

func (x *RelationDelta) GetAddTags() []string {
	if x != nil {
		return x.AddTags
	}
	return nil
}

type RememberAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int64                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Deduped       int64                  `protobuf:"varint,2,opt,name=deduped,proto3" json:"deduped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RememberAck) Reset() {
	*x = RememberAck{}
	mi := &file_mesa_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RememberAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RememberAck) ProtoMessage() {}

func (x *RememberAck) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RememberAck.ProtoReflect.Descriptor instead.
func (*RememberAck) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{14}
}

func (x *RememberAck) GetAccepted() int64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *RememberAck) GetDeduped() int64 {
	if x != nil {
		return x.Deduped
	}
	return 0
}

// Provisioning carries the authoritative persona as JSON bytes (one schema
// source: the Go persona structs) — the host compiles the func-valued pearl
// table locally, so it cannot cross the wire.
type Provisioning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonaJson   []byte                 `protobuf:"bytes,1,opt,name=persona_json,json=personaJson,proto3" json:"persona_json,omitempty"`
	Prose         string                 `protobuf:"bytes,2,opt,name=prose,proto3" json:"prose,omitempty"`
	Goals         []string               `protobuf:"bytes,3,rep,name=goals,proto3" json:"goals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provisioning) Reset() {
	*x = Provisioning{}
	mi := &file_mesa_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provisioning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provisioning) ProtoMessage() {}

func (x *Provisioning) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provisioning.ProtoReflect.Descriptor instead.
func (*Provisioning) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{15}
}

func (x *Provisioning) GetPersonaJson() []byte {
	if x != nil {
		return x.PersonaJson
	}
	return nil
}

func (x *Provisioning) GetProse() string {
	if x != nil {
		return x.Prose
	}
	return ""
}

func (x *Provisioning) GetGoals() []string {
	if x != nil {
		return x.Goals
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *HostRef               `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	LastAppliedId int64                  `protobuf:"varint,2,opt,name=last_applied_id,json=lastAppliedId,proto3" json:"last_applied_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_mesa_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{16}
}

func (x *SubscribeRequest) GetHost() *HostRef {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *SubscribeRequest) GetLastAppliedId() int64 {
	if x != nil {
		return x.LastAppliedId
	}
	return 0
}

type Directive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // monotonic per host; ignore id <= last_applied
	Kind          DirectiveKind          `protobuf:"varint,2,opt,name=kind,proto3,enum=westworld.mesa.v2.DirectiveKind" json:"kind,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // typed by kind
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directive) Reset() {
	*x = Directive{}
	mi := &file_mesa_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directive) ProtoMessage() {}

func (x *Directive) ProtoReflect() protoreflect.Message {
	mi := &file_mesa_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directive.ProtoReflect.Descriptor instead.
func (*Directive) Descriptor() ([]byte, []int) {
	return file_mesa_proto_rawDescGZIP(), []int{17}
}

func (x *Directive) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Directive) GetKind() DirectiveKind {
	if x != nil {
		return x.Kind
	}
	return DirectiveKind_DIRECTIVE_UNSPECIFIED
}

func (x *Directive) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_mesa_proto protoreflect.FileDescriptor

const file_mesa_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mesa.proto\x12\x11westworld.mesa.v2\"K\n" +
	"\aHostRef\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12'\n" +
	"\x0fpersona_version\x18\x02 \x01(\tR\x0epersonaVersion\"Z\n" +
	"\x06Affect\x12\x16\n" +
	"\x06stress\x18\x01 \x01(\x01R\x06stress\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12\x18\n" +
	"\avalence\x18\x03 \x01(\x01R\avalence\"\x80\x01\n" +
	"\bChatTurn\x12.\n" +
	"\x04host\x18\x01 \x01(\v2\x1a.westworld.mesa.v2.HostRefR\x04host\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06recent\x18\x04 \x03(\tR\x06recent\"5\n" +
	"\tChatReply\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05speak\x18\x02 \x01(\bR\x05speak\"\xdd\x02\n" +
	"\tSituation\x12.\n" +
	"\x04host\x18\x01 \x01(\v2\x1a.westworld.mesa.v2.HostRefR\x04host\x12\x12\n" +
	"\x04goal\x18\x02 \x01(\tR\x04goal\x12\x18\n" +
	"\atrigger\x18\x03 \x01(\tR\atrigger\x12.\n" +
	"\x05world\x18\x04 \x01(\v2\x18.westworld.mesa.v2.WorldR\x05world\x12\x16\n" +
	"\x06recent\x18\x05 \x03(\tR\x06recent\x121\n" +
	"\x06affect\x18\x06 \x01(\v2\x19.westworld.mesa.v2.AffectR\x06affect\x12=\n" +
	"\x05hints\x18\a \x03(\v2'.westworld.mesa.v2.Situation.HintsEntryR\x05hints\x1a8\n" +
	"\n" +
	"HintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x02\n" +
	"\x05World\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x15\n" +
	"\x06hp_cur\x18\x04 \x01(\x05R\x05hpCur\x12\x15\n" +
	"\x06hp_max\x18\x05 \x01(\x05R\x05hpMax\x12!\n" +
	"\fcombat_level\x18\x06 \x01(\x05R\vcombatLevel\x12\x18\n" +
	"\afatigue\x18\a \x01(\x01R\afatigue\x12\x19\n" +
	"\binv_free\x18\b \x01(\x05R\ainvFree\x12\x1f\n" +
	"\vinv_summary\x18\t \x03(\tR\n" +
	"invSummary\x12\x1f\n" +
	"\vnearby_npcs\x18\n" +
	" \x03(\tR\n" +
	"nearbyNpcs\x12%\n" +
	"\x0enearby_players\x18\v \x03(\tR\rnearbyPlayers\"\xc8\x02\n" +
	"\x04Move\x12/\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.westworld.mesa.v2.MoveKindR\x04kind\x12\x1c\n" +
	"\treasoning\x18\x02 \x01(\tR\treasoning\x12!\n" +
	"\froutine_path\x18\x03 \x01(\tR\vroutinePath\x12!\n" +
	"\froutine_name\x18\x04 \x01(\tR\vroutineName\x12\x1d\n" +
	"\n" +
	"dsl_source\x18\x05 \x01(\tR\tdslSource\x12 \n" +
	"\vquarantined\x18\x06 \x01(\bR\vquarantined\x12\x12\n" +
	"\x04args\x18\a \x03(\tR\x04args\x12\x12\n" +
	"\x04verb\x18\b \x01(\tR\x04verb\x12\x1f\n" +
	"\vaction_args\x18\t \x03(\tR\n" +
	"actionArgs\x12!\n" +
	"\fidle_seconds\x18\n" +
	" \x01(\x05R\vidleSeconds\"\xa1\x01\n" +
	"\x06Choice\x12.\n" +
	"\x04host\x18\x01 \x01(\v2\x1a.westworld.mesa.v2.HostRefR\x04host\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x121\n" +
	"\x06affect\x18\x04 \x01(\v2\x19.westworld.mesa.v2.AffectR\x06affect\"\xa9\x01\n" +
	"\bDecision\x12\x16\n" +
	"\x06choice\x18\x01 \x01(\tR\x06choice\x12\x1c\n" +
	"\treasoning\x18\x02 \x01(\tR\treasoning\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1b\n" +
	"\tcache_key\x18\x04 \x01(\tR\bcacheKey\x12*\n" +
	"\x11cache_ttl_seconds\x18\x05 \x01(\x03R\x0fcacheTtlSeconds\"\x92\x01\n" +
	"\x05Query\x12.\n" +
	"\x04host\x18\x01 \x01(\v2\x1a.westworld.mesa.v2.HostRefR\x04host\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x120\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1c.westworld.mesa.v2.QueryKindR\x04kind\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\"F\n" +
	"\fKnowledgeSet\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .westworld.mesa.v2.KnowledgeItemR\x05items\"\x9d\x01\n" +
	"\rKnowledgeItem\x120\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1c.westworld.mesa.v2.QueryKindR\x04kind\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x10\n" +
	"\x03dsl\x18\x03 \x01(\tR\x03dsl\x12\x1e\n" +
	"\n" +
	"provenance\x18\x04 \x01(\tR\n" +
	"provenance\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\"\x85\x03\n" +
	"\aEpisode\x12.\n" +
	"\x04host\x18\x01 \x01(\v2\x1a.westworld.mesa.v2.HostRefR\x04host\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"importance\x18\x05 \x01(\x01R\n" +
	"importance\x12(\n" +
	"\x10occurred_at_unix\x18\x06 \x01(\x03R\x0eoccurredAtUnix\x12<\n" +
	"\brelation\x18\a \x01(\v2 .westworld.mesa.v2.RelationDeltaR\brelation\x128\n" +
	"\x04tags\x18\b \x03(\v2$.westworld.mesa.v2.Episode.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbf\x01\n" +
	"\rRelationDelta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\ad_alpha\x18\x02 \x01(\x01R\x06dAlpha\x12\x15\n" +
	"\x06d_beta\x18\x03 \x01(\x01R\x05dBeta\x12!\n" +
	"\fd_encounters\x18\x04 \x01(\x05R\vdEncounters\x12,\n" +
	"\x12total_value_traded\x18\x05 \x01(\x01R\x10totalValueTraded\x12\x19\n" +
	"\badd_tags\x18\x06 \x03(\tR\aaddTags\"C\n" +
	"\vRememberAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x03R\baccepted\x12\x18\n" +
	"\adeduped\x18\x02 \x01(\x03R\adeduped\"]\n" +
	"\fProvisioning\x12!\n" +
	"\fpersona_json\x18\x01 \x01(\fR\vpersonaJson\x12\x14\n" +
	"\x05prose\x18\x02 \x01(\tR\x05prose\x12\x14\n" +
	"\x05goals\x18\x03 \x03(\tR\x05goals\"j\n" +
	"\x10SubscribeRequest\x12.\n" +
	"\x04host\x18\x01 \x01(\v2\x1a.westworld.mesa.v2.HostRefR\x04host\x12&\n" +
	"\x0flast_applied_id\x18\x02 \x01(\x03R\rlastAppliedId\"k\n" +
	"\tDirective\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x124\n" +
	"\x04kind\x18\x02 \x01(\x0e2 .westworld.mesa.v2.DirectiveKindR\x04kind\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload*K\n" +
	"\bMoveKind\x12\x0f\n" +
	"\vRUN_ROUTINE\x10\x00\x12\x11\n" +
	"\rWRITE_ROUTINE\x10\x01\x12\x11\n" +
	"\rDIRECT_ACTION\x10\x02\x12\b\n" +
	"\x04IDLE\x10\x03*J\n" +
	"\tQueryKind\x12\a\n" +
	"\x03ANY\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCEDURAL\x10\x01\x12\n" +
	"\n" +
	"\x06ENTITY\x10\x02\x12\f\n" +
	"\bEPISODIC\x10\x03\x12\n" +
	"\n" +
	"\x06SOCIAL\x10\x04*\xa3\x01\n" +
	"\rDirectiveKind\x12\x19\n" +
	"\x15DIRECTIVE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eROUTINE_UPSERT\x10\x01\x12\x11\n" +
	"\rPEARL_REFRESH\x10\x02\x12\x14\n" +
	"\x10PERSONA_REVISION\x10\x03\x12\x11\n" +
	"\rGOAL_REVISION\x10\x04\x12\x0f\n" +
	"\vTRUST_DECAY\x10\x05\x12\x16\n" +
	"\x12REVERIE_REBASELINE\x10\x062\xc9\x01\n" +
	"\x04Game\x12<\n" +
	"\x03Act\x12\x1c.westworld.mesa.v2.Situation\x1a\x17.westworld.mesa.v2.Move\x12@\n" +
	"\x06Decide\x12\x19.westworld.mesa.v2.Choice\x1a\x1b.westworld.mesa.v2.Decision\x12A\n" +
	"\x04Chat\x12\x1b.westworld.mesa.v2.ChatTurn\x1a\x1c.westworld.mesa.v2.ChatReply2P\n" +
	"\tKnowledge\x12C\n" +
	"\x06Recall\x12\x18.westworld.mesa.v2.Query\x1a\x1f.westworld.mesa.v2.KnowledgeSet2S\n" +
	"\aJournal\x12H\n" +
	"\bRemember\x12\x1a.westworld.mesa.v2.Episode\x1a\x1e.westworld.mesa.v2.RememberAck(\x012\xa3\x01\n" +
	"\tProvision\x12D\n" +
	"\x05Fetch\x12\x1a.westworld.mesa.v2.HostRef\x1a\x1f.westworld.mesa.v2.Provisioning\x12P\n" +
	"\tSubscribe\x12#.westworld.mesa.v2.SubscribeRequest\x1a\x1c.westworld.mesa.v2.Directive0\x01B1Z/github.com/gen0cide/westworld/mesa/proto;mesapbb\x06proto3"

var (
	file_mesa_proto_rawDescOnce sync.Once
	file_mesa_proto_rawDescData []byte
)

func file_mesa_proto_rawDescGZIP() []byte {
	file_mesa_proto_rawDescOnce.Do(func() {
		file_mesa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesa_proto_rawDesc), len(file_mesa_proto_rawDesc)))
	})
	return file_mesa_proto_rawDescData
}

var file_mesa_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mesa_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_mesa_proto_goTypes = []any{
	(MoveKind)(0),            // 0: westworld.mesa.v2.MoveKind
	(QueryKind)(0),           // 1: westworld.mesa.v2.QueryKind
	(DirectiveKind)(0),       // 2: westworld.mesa.v2.DirectiveKind
	(*HostRef)(nil),          // 3: westworld.mesa.v2.HostRef
	(*Affect)(nil),           // 4: westworld.mesa.v2.Affect
	(*ChatTurn)(nil),         // 5: westworld.mesa.v2.ChatTurn
	(*ChatReply)(nil),        // 6: westworld.mesa.v2.ChatReply
	(*Situation)(nil),        // 7: westworld.mesa.v2.Situation
	(*World)(nil),            // 8: westworld.mesa.v2.World
	(*Move)(nil),             // 9: westworld.mesa.v2.Move
	(*Choice)(nil),           // 10: westworld.mesa.v2.Choice
	(*Decision)(nil),         // 11: westworld.mesa.v2.Decision
	(*Query)(nil),            // 12: westworld.mesa.v2.Query
	(*KnowledgeSet)(nil),     // 13: westworld.mesa.v2.KnowledgeSet
	(*KnowledgeItem)(nil),    // 14: westworld.mesa.v2.KnowledgeItem
	(*Episode)(nil),          // 15: westworld.mesa.v2.Episode
	(*RelationDelta)(nil),    // 16: westworld.mesa.v2.RelationDelta
	(*RememberAck)(nil),      // 17: westworld.mesa.v2.RememberAck
	(*Provisioning)(nil),     // 18: westworld.mesa.v2.Provisioning
	(*SubscribeRequest)(nil), // 19: westworld.mesa.v2.SubscribeRequest
	(*Directive)(nil),        // 20: westworld.mesa.v2.Directive
	nil,                      // 21: westworld.mesa.v2.Situation.HintsEntry
	nil,                      // 22: westworld.mesa.v2.Episode.TagsEntry
}
var file_mesa_proto_depIdxs = []int32{
	3,  // 0: westworld.mesa.v2.ChatTurn.host:type_name -> westworld.mesa.v2.HostRef
	3,  // 1: westworld.mesa.v2.Situation.host:type_name -> westworld.mesa.v2.HostRef
	8,  // 2: westworld.mesa.v2.Situation.world:type_name -> westworld.mesa.v2.World
	4,  // 3: westworld.mesa.v2.Situation.affect:type_name -> westworld.mesa.v2.Affect
	21, // 4: westworld.mesa.v2.Situation.hints:type_name -> westworld.mesa.v2.Situation.HintsEntry
	0,  // 5: westworld.mesa.v2.Move.kind:type_name -> westworld.mesa.v2.MoveKind
	3,  // 6: westworld.mesa.v2.Choice.host:type_name -> westworld.mesa.v2.HostRef
	4,  // 7: westworld.mesa.v2.Choice.affect:type_name -> westworld.mesa.v2.Affect
	3,  // 8: westworld.mesa.v2.Query.host:type_name -> westworld.mesa.v2.HostRef
	1,  // 9: westworld.mesa.v2.Query.kind:type_name -> westworld.mesa.v2.QueryKind
	14, // 10: westworld.mesa.v2.KnowledgeSet.items:type_name -> westworld.mesa.v2.KnowledgeItem
	1,  // 11: westworld.mesa.v2.KnowledgeItem.kind:type_name -> westworld.mesa.v2.QueryKind
	3,  // 12: westworld.mesa.v2.Episode.host:type_name -> westworld.mesa.v2.HostRef
	16, // 13: westworld.mesa.v2.Episode.relation:type_name -> westworld.mesa.v2.RelationDelta
	22, // 14: westworld.mesa.v2.Episode.tags:type_name -> westworld.mesa.v2.Episode.TagsEntry
	3,  // 15: westworld.mesa.v2.SubscribeRequest.host:type_name -> westworld.mesa.v2.HostRef
	2,  // 16: westworld.mesa.v2.Directive.kind:type_name -> westworld.mesa.v2.DirectiveKind
	7,  // 17: westworld.mesa.v2.Game.Act:input_type -> westworld.mesa.v2.Situation
	10, // 18: westworld.mesa.v2.Game.Decide:input_type -> westworld.mesa.v2.Choice
	5,  // 19: westworld.mesa.v2.Game.Chat:input_type -> westworld.mesa.v2.ChatTurn
	12, // 20: westworld.mesa.v2.Knowledge.Recall:input_type -> westworld.mesa.v2.Query
	15, // 21: westworld.mesa.v2.Journal.Remember:input_type -> westworld.mesa.v2.Episode
	3,  // 22: westworld.mesa.v2.Provision.Fetch:input_type -> westworld.mesa.v2.HostRef
	19, // 23: westworld.mesa.v2.Provision.Subscribe:input_type -> westworld.mesa.v2.SubscribeRequest
	9,  // 24: westworld.mesa.v2.Game.Act:output_type -> westworld.mesa.v2.Move
	11, // 25: westworld.mesa.v2.Game.Decide:output_type -> westworld.mesa.v2.Decision
	6,  // 26: westworld.mesa.v2.Game.Chat:output_type -> westworld.mesa.v2.ChatReply
	13, // 27: westworld.mesa.v2.Knowledge.Recall:output_type -> westworld.mesa.v2.KnowledgeSet
	17, // 28: westworld.mesa.v2.Journal.Remember:output_type -> westworld.mesa.v2.RememberAck
	18, // 29: westworld.mesa.v2.Provision.Fetch:output_type -> westworld.mesa.v2.Provisioning
	20, // 30: westworld.mesa.v2.Provision.Subscribe:output_type -> westworld.mesa.v2.Directive
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_mesa_proto_init() }
func file_mesa_proto_init() {
	if File_mesa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesa_proto_rawDesc), len(file_mesa_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_mesa_proto_goTypes,
		DependencyIndexes: file_mesa_proto_depIdxs,
		EnumInfos:         file_mesa_proto_enumTypes,
		MessageInfos:      file_mesa_proto_msgTypes,
	}.Build()
	File_mesa_proto = out.File
	file_mesa_proto_goTypes = nil
	file_mesa_proto_depIdxs = nil
}
