package spec

import "fmt"

// ActionKind categorizes a callable by its cost/effect profile.
// Most validator and bridge decisions derive from this — bang
// eligibility, in-proc/in-require/in-handler restrictions,
// subscription-safety in `when` predicates.
type ActionKind int

const (
	// PrimaryAction mutates game state by sending packets. Blocks
	// until server confirms or fails. Yields to the event scheduler
	// before/after the call. Always bang-eligible.
	PrimaryAction ActionKind = iota

	// Primitive is a local-only callable: wait, wait_until, note.
	// Some yield (wait, wait_until); none can fail in the typed
	// sense (cancellation flows through ctx). Never bang-eligible.
	Primitive

	// LLMStdlib reaches up to the brain (Sonnet/Haiku). Yields,
	// expensive ($), rate-limited. Bang-eligible.
	LLMStdlib

	// MemoryStdlib touches mesa or waits for external events
	// (recall, relation_with, observe, wait_for_chat). Yields
	// (network), can fail. Bang-eligible.
	MemoryStdlib

	// PersonaRead is a pure local read of persona/identity state
	// (mood, motivation, host.persona.*). No yield, no failure.
	// Never bang-eligible.
	PersonaRead
)

func (k ActionKind) String() string {
	switch k {
	case PrimaryAction:
		return "PrimaryAction"
	case Primitive:
		return "Primitive"
	case LLMStdlib:
		return "LLMStdlib"
	case MemoryStdlib:
		return "MemoryStdlib"
	case PersonaRead:
		return "PersonaRead"
	}
	return fmt.Sprintf("ActionKind(%d)", int(k))
}

// ActionSpec describes one DSL callable in full. The validator
// derives every check from these fields; the bridge derives every
// registration from them. Adding a new callable is a single row.
type ActionSpec struct {
	// Name is the DSL identifier. Lowercase snake_case. The bang
	// variant (if eligible) is the same name with a trailing `!` —
	// auto-generated by the bridge.
	Name string

	// Kind drives bang eligibility and context restrictions; see
	// the constants above.
	Kind ActionKind

	// MinArgs / MaxArgs bound positional arity. MaxArgs == -1
	// means unbounded.
	MinArgs int
	MaxArgs int

	// Params lists positional parameter names in declaration order.
	// Used by tooling (REPL `.help`, doc generation) and to
	// validate named-argument calls. Empty for nullary callables.
	Params []string

	// DocSummary is one line describing what the callable does.
	// Shown by REPL `.help <name>` and emitted into the
	// auto-generated docs.
	DocSummary string

	// NotYetImplemented marks a spec-defined callable for which
	// the Go wrapper is still a stub (returns
	// Fail(NOT_IMPLEMENTED, name)). Used by the consistency test
	// to distinguish "spec drift" from "planned but not built."
	NotYetImplemented bool
}

// BangEligible returns true iff `<name>!` is a valid identifier.
// PrimaryAction / LLMStdlib / MemoryStdlib return *CallResult and
// therefore have bang variants. Primitives and persona reads
// don't.
func (s ActionSpec) BangEligible() bool {
	switch s.Kind {
	case PrimaryAction, LLMStdlib, MemoryStdlib:
		return true
	}
	return false
}

// IsAction returns true for PrimaryAction only — callables that
// mutate game state via outbound packets. Used by the validator
// to enforce "no actions inside proc/require."
func (s ActionSpec) IsAction() bool { return s.Kind == PrimaryAction }

// AllowedInProc reports whether the callable may appear inside a
// `proc` body. Procs are pure helpers: PersonaRead and
// MemoryStdlib (queries) are fine; everything else is forbidden.
func (s ActionSpec) AllowedInProc() bool {
	switch s.Kind {
	case PersonaRead, MemoryStdlib:
		return true
	}
	return false
}

// AllowedInRequire mirrors AllowedInProc — require blocks are
// pure-expression precondition checks.
func (s ActionSpec) AllowedInRequire() bool { return s.AllowedInProc() }

// AllowedInHandler reports whether the callable may appear inside
// an `on event(...)` handler body. Handlers must not extend-yield
// beyond a single primary action — so wait and wait_until are
// forbidden (extended sleeps), but primary actions themselves are
// fine (they yield briefly for server confirmation).
//
// `select` is a statement, not a callable, and is handled
// separately by the validator's statement check.
func (s ActionSpec) AllowedInHandler() bool {
	if s.Kind == Primitive && (s.Name == "wait" || s.Name == "wait_until") {
		return false
	}
	return true
}

// SubscriptionSafe reports whether the callable may appear inside
// a `when expr { ... }` predicate or a `select` case condition.
// Predicates re-evaluate frequently (every action boundary + every
// tick), so anything expensive or stateful is forbidden. Only
// pure reads (PersonaRead, MemoryStdlib) are safe.
func (s ActionSpec) SubscriptionSafe() bool {
	switch s.Kind {
	case PersonaRead, MemoryStdlib:
		return true
	}
	return false
}

// Actions is the canonical, ordered list of every DSL callable.
// Order is purely documentational — lookups go through ByName.
//
// When adding a new entry: pick the appropriate ActionKind, fill
// in arity + params + DocSummary, and add the Go wrapper in
// runtime/dsl_actions.go plus the registration in
// runtime/dsl_bridge.go (the consistency test will flag a missing
// wrapper).
var Actions = []ActionSpec{
	// ===== Primary actions — mutate game state =====

	// Movement
	{Name: "walk_to", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 2,
		Params: []string{"x", "y"},
		DocSummary: "Walk to (x, y); blocks until arrived or fails."},

	// Combat
	{Name: "attack", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 1,
		Params: []string{"target"},
		DocSummary: "Initiate combat with an NPC or player."},
	{Name: "talk_to", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 1,
		Params: []string{"npc"},
		DocSummary: "Walk adjacent and open the NPC's dialog."},
	{Name: "answer", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 1,
		Params: []string{"option_index"},
		DocSummary: "Choose a numbered option in the current NPC dialog."},

	// Items
	{Name: "drop", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 2,
		Params: []string{"item"},
		DocSummary: "Drop the item (slot or item-view) to the ground."},
	{Name: "pick_up", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 1,
		Params: []string{"ground_item"},
		DocSummary: "Walk to and pick up a ground item; returns the item on success."},
	{Name: "eat", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 1,
		Params: []string{"item"},
		DocSummary: "Use an item (Eat/Drink/Bury — server decides by item def)."},

	// Banking
	{Name: "open_bank", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 1,
		Params: []string{"banker"},
		DocSummary: "Open the bank UI by talking to a banker NPC."},
	{Name: "deposit", Kind: PrimaryAction, MinArgs: 2, MaxArgs: 2,
		Params: []string{"item", "amount"},
		DocSummary: "Deposit `amount` of the item into the open bank."},
	{Name: "withdraw", Kind: PrimaryAction, MinArgs: 2, MaxArgs: 2,
		Params: []string{"item", "amount"},
		DocSummary: "Withdraw `amount` of the item from the open bank."},
	{Name: "close_bank", Kind: PrimaryAction, MinArgs: 0, MaxArgs: 0,
		DocSummary: "Close the bank UI."},

	// Social
	{Name: "say", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 1,
		Params: []string{"message"},
		DocSummary: "Public chat message."},
	{Name: "whisper", Kind: PrimaryAction, MinArgs: 2, MaxArgs: 2,
		Params: []string{"to", "message"},
		DocSummary: "Private message to another player."},
	{Name: "command", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 1,
		Params: []string{"cmd"},
		DocSummary: "Send an admin command (without the leading ::). Requires admin permissions on the server. E.g. command(\"tele 103 532\")."},
	{Name: "use", Kind: PrimaryAction, MinArgs: 2, MaxArgs: 2,
		Params: []string{"item", "target"},
		DocSummary: "Use one item on a target. Target kind picks the opcode: boundary (key on door), item (chisel on gem), scenery (log on fire). Cooking/smelting collapse to use(raw, fire) / use(ore, furnace) — convenience verbs are routine-level wrappers."},
	{Name: "interact_at", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 2,
		Params: []string{"position", "option"},
		DocSummary: "Fire the primary (option=1, default) or secondary (option=2) click on a scenery tile. The verb depends on the def — \"Chop\" on a tree, \"Mine\" on a rock, \"Climb-Up\" on a ladder, etc. interact_at(world.locs.rocks.nearest()) is the canonical mining open."},
	{Name: "distance_to", Kind: Primitive, MinArgs: 1, MaxArgs: 1,
		Params: []string{"target"},
		DocSummary: "Chebyshev distance from self.position to target (any view with .x/.y, or a {x, y} position). Returns Int (tiles). Used for proximity checks: if distance_to(target) > 3 { walk_to(target.position) }."},
	{Name: "in_region", Kind: Primitive, MinArgs: 4, MaxArgs: 4,
		Params: []string{"x1", "y1", "x2", "y2"},
		DocSummary: "Returns true iff self.position is inside the rectangle (x1,y1)..(x2,y2) (inclusive). Geometry helper for area-restricted routines — e.g. if in_region(120, 640, 135, 660) { handle_lumbridge_courtyard() }."},
	{Name: "walk_path", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 1,
		Params: []string{"corners"},
		DocSummary: "Send a pre-planned multi-corner walk. corners is a list of [x, y] pairs (max 25 per RSC packet). The server interpolates each segment. Used to commit to a route the routine planned itself; for grid-bounded routes use walk_to (which pathfinds for you)."},
	{Name: "is_reachable", Kind: Primitive, MinArgs: 1, MaxArgs: 2,
		Params: []string{"x", "y"},
		DocSummary: "Returns true iff the local pathfinder can reach (x, y) from self.position. Bounded by the 96-tile FOV grid; for cross-region checks, use sequential is_reachable calls along a planned route. Pure (no packet sent)."},
	{Name: "wait_for_dialog", Kind: Primitive, MinArgs: 0, MaxArgs: 1,
		Params: []string{"timeout_seconds"},
		DocSummary: "Block until an NPC dialog menu opens, OR until timeout_seconds elapses (default 5). Returns true if a menu landed, false on timeout. Cleaner than `wait 5; if world.dialog.is_open` polling."},
	{Name: "trade_request", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 1,
		Params: []string{"player"},
		DocSummary: "Send a trade request to a player (accepts a player-view or a server-index Int). Pathfinds adjacent first. Updates world.trade phase to \"request_sent\"."},
	{Name: "accept_trade", Kind: PrimaryAction, MinArgs: 0, MaxArgs: 0,
		DocSummary: "Accept a pending trade request received via the `on trade_request` event. Server then sends trade_opened to both sides."},
	{Name: "decline_trade", Kind: PrimaryAction, MinArgs: 0, MaxArgs: 0,
		DocSummary: "Decline a pending or active trade. Marks world.trade closed (not-completed)."},
	{Name: "offer_trade", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 1,
		Params: []string{"items"},
		DocSummary: "Set the host's offered items. items is a list of [item_id, amount] pairs. Replaces any prior offer. Both sides' accept flags reset on offer change (server rule)."},
	{Name: "confirm_trade", Kind: PrimaryAction, MinArgs: 0, MaxArgs: 0,
		DocSummary: "Click \"Accept\" in the trade window. Two clicks needed total — first on the offer screen, second on the confirm screen. World state tracks which step you're on."},
	// world.dialog.* accessors are surfaced as Getters on the
	// world view, not standalone builtins — spec entries for those
	// would be document-only since they're accessor paths, not
	// callables. Documented in docs/lang/state.md.

	// Session
	{Name: "logout", Kind: PrimaryAction, MinArgs: 0, MaxArgs: 0,
		DocSummary: "Initiate logout."},

	// Skills — not yet implemented as Host methods.
	{Name: "mine", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 1,
		Params: []string{"rock"},
		DocSummary: "Mine a rock (skill not yet implemented).",
		NotYetImplemented: true},
	{Name: "fish", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 1,
		Params: []string{"spot"},
		DocSummary: "Fish at a spot (skill not yet implemented).",
		NotYetImplemented: true},
	{Name: "chop", Kind: PrimaryAction, MinArgs: 1, MaxArgs: 1,
		Params: []string{"tree"},
		DocSummary: "Chop a tree (skill not yet implemented).",
		NotYetImplemented: true},
	{Name: "cook", Kind: PrimaryAction, MinArgs: 2, MaxArgs: 2,
		Params: []string{"item", "fire"},
		DocSummary: "Cook an item on a fire (skill not yet implemented).",
		NotYetImplemented: true},
	{Name: "cast", Kind: PrimaryAction, MinArgs: 2, MaxArgs: 2,
		Params: []string{"spell", "target"},
		DocSummary: "Cast a spell on a target (magic not yet implemented).",
		NotYetImplemented: true},

	// ===== Primitives — local, no typed failure, no bang =====

	{Name: "wait", Kind: Primitive, MinArgs: 1, MaxArgs: 1,
		Params: []string{"seconds"},
		DocSummary: "Sleep for N seconds (or pick from a range like 2.8..4.5)."},
	{Name: "wait_until", Kind: Primitive, MinArgs: 1, MaxArgs: 1,
		Params: []string{"predicate"},
		DocSummary: "Block until the predicate evaluates truthy.",
		NotYetImplemented: true},
	{Name: "note", Kind: Primitive, MinArgs: 1, MaxArgs: 1,
		Params: []string{"text"},
		DocSummary: "Write a lightweight journal entry (no LLM)."},

	// ===== LLM stdlib — bang-eligible =====

	{Name: "contemplate_reality", Kind: LLMStdlib, MinArgs: 0, MaxArgs: 1,
		Params: []string{"question"},
		DocSummary: "Open-ended LLM decision; returns a short string code. Stub strategist returns canned answers; real LLM lands in Phase 4."},
	{Name: "evaluate", Kind: LLMStdlib, MinArgs: 1, MaxArgs: 1,
		Params: []string{"situation"},
		DocSummary: "0-1 numeric assessment via strategist.Confidence. Stub returns deterministic confidence."},
	{Name: "decide", Kind: LLMStdlib, MinArgs: 1, MaxArgs: 2,
		Params: []string{"options", "context"},
		DocSummary: "Pick one of caller-supplied options. Stub returns options[0]."},
	{Name: "exec", Kind: LLMStdlib, MinArgs: 1, MaxArgs: 1,
		Params: []string{"prompt"},
		DocSummary: "LLM authors and runs a fresh DSL fragment inline.",
		NotYetImplemented: true},
	{Name: "improvise", Kind: LLMStdlib, MinArgs: 1, MaxArgs: 1,
		Params: []string{"prompt"},
		DocSummary: "One-shot DSL fragment; not retained.",
		NotYetImplemented: true},
	{Name: "reflect_now", Kind: LLMStdlib, MinArgs: 0, MaxArgs: 0,
		DocSummary: "Synchronous reflection pass; returns a reflection id.",
		NotYetImplemented: true},

	// ===== Memory / external stdlib — bang-eligible =====

	{Name: "recall", Kind: MemoryStdlib, MinArgs: 1, MaxArgs: 2,
		Params: []string{"query", "top"},
		DocSummary: "Top-K vector search over episodic memory. Stub returns canned reflections; real mesa retrieval lands in Phase 3."},
	{Name: "relation_with", Kind: MemoryStdlib, MinArgs: 1, MaxArgs: 1,
		Params: []string{"name"},
		DocSummary: "Relational record for a named player. Stub returns persona[\"relation:NAME\"] or first reflection."},
	{Name: "wait_for_chat", Kind: MemoryStdlib, MinArgs: 0, MaxArgs: 2,
		Params: []string{"timeout_seconds", "from"},
		DocSummary: "Block until a chat message arrives (optionally filtered).",
		NotYetImplemented: true},
	{Name: "observe", Kind: MemoryStdlib, MinArgs: 1, MaxArgs: 2,
		Params: []string{"target", "ticks"},
		DocSummary: "Watch an entity for N ticks; returns activity summary.",
		NotYetImplemented: true},

	// ===== Persona reads — pure, no bang =====

	{Name: "mood", Kind: PersonaRead, MinArgs: 0, MaxArgs: 0,
		DocSummary: "Current emotional-state weights map.",
		NotYetImplemented: true},
	{Name: "motivation", Kind: PersonaRead, MinArgs: 0, MaxArgs: 0,
		DocSummary: "North-star goal + current focus.",
		NotYetImplemented: true},
}

// byName is built once at init for O(1) lookups.
var byName map[string]*ActionSpec

func init() {
	byName = make(map[string]*ActionSpec, len(Actions))
	for i := range Actions {
		byName[Actions[i].Name] = &Actions[i]
	}
}

// ByName returns the ActionSpec for `name` (without trailing `!`)
// and ok=true if found.
func ByName(name string) (*ActionSpec, bool) {
	s, ok := byName[name]
	return s, ok
}

// StripBang removes a trailing `!` from `name` and reports whether
// it was present. Convenience for callers that want to check both
// the bang and base names.
func StripBang(name string) (base string, hadBang bool) {
	if len(name) > 1 && name[len(name)-1] == '!' {
		return name[:len(name)-1], true
	}
	return name, false
}
