// Package script embeds a Starlark interpreter and exposes the
// runtime.Host action surface as a Starlark module. Scripts can be
// hand-written for tests or generated by an LLM brain.
//
// Starlark was chosen over Lua / Tengo because:
//   - Python-flavoured syntax: LLMs generate it well; humans read it easily.
//   - Sandboxed: no filesystem / network / OS access from script land.
//   - Deterministic: no clock, no map iteration order.
//   - Mature implementation (Bazel, Buck) with a stable Go API.
//
// The exposed module is `westworld`. A typical script looks like:
//
//	def main():
//	    westworld.say("looking around")
//	    print(westworld.look_around(radius = 6))
//	    npcs = westworld.nearby_npcs()
//	    for n in npcs:
//	        if n["name"] == "Goblin" and n["attackable"]:
//	            westworld.attack_npc(n["index"])
//	            break
//
//	main()
package script

import (
	"context"
	"fmt"
	"os"
	"sync"
	"time"

	"go.starlark.net/starlark"
	"go.starlark.net/syntax"

	"github.com/gen0cide/westworld/action"
	"github.com/gen0cide/westworld/runtime"
	"github.com/gen0cide/westworld/world"
)

// Engine wraps a single Starlark thread bound to one Host. Engines
// are NOT thread-safe; one Engine per bot.
type Engine struct {
	host *runtime.Host
	mu   sync.Mutex
}

// New creates an Engine bound to the given Host. The host should be
// fully connected (Host.Connect + Host.Run goroutine running) before
// you call Run.
func New(host *runtime.Host) *Engine {
	return &Engine{host: host}
}

// RunFile loads and executes a Starlark script from `path`. The script
// runs to completion (or until ctx cancels). Errors include both
// Starlark syntax/runtime errors and any underlying network errors
// from action calls.
func (e *Engine) RunFile(ctx context.Context, path string) error {
	src, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("script: read %q: %w", path, err)
	}
	return e.RunString(ctx, path, string(src))
}

// RunString executes inline Starlark source. `name` is used in
// stack traces.
func (e *Engine) RunString(ctx context.Context, name, src string) error {
	e.mu.Lock()
	defer e.mu.Unlock()

	thread := &starlark.Thread{
		Name: "westworld:" + name,
		Print: func(t *starlark.Thread, msg string) {
			fmt.Println(msg)
		},
	}
	// Stash the context so module builtins can pick it up — Starlark
	// doesn't have a context concept of its own.
	thread.SetLocal("ctx", ctx)
	thread.SetLocal("host", e.host)

	predeclared := e.predeclared()
	opts := &syntax.FileOptions{
		Set:             true,
		While:           true,
		TopLevelControl: true,
		Recursion:       true,
		GlobalReassign:  true,
	}
	_, err := starlark.ExecFileOptions(opts, thread, name, src, predeclared)
	return err
}

// predeclared returns the global Starlark names available to every
// script — the bot's full action surface, exposed as flat builtins
// (no namespace prefix needed). Scripts call `look_around()` and
// `attack_npc(idx)` directly.
func (e *Engine) predeclared() starlark.StringDict {
	return starlark.StringDict{
		// Perception.
		"look_around":     starlark.NewBuiltin("look_around", b_lookAround),
		"self_state":      starlark.NewBuiltin("self_state", b_selfState),
		"nearby_npcs":     starlark.NewBuiltin("nearby_npcs", b_nearbyNpcs),
		"nearby_players":  starlark.NewBuiltin("nearby_players", b_nearbyPlayers),
		"ground_items":    starlark.NewBuiltin("ground_items", b_groundItems),
		"inventory":       starlark.NewBuiltin("inventory", b_inventory),
		"examine_npc":     starlark.NewBuiltin("examine_npc", b_examineNpc),
		"examine_item":    starlark.NewBuiltin("examine_item", b_examineItem),
		"examine_scenery": starlark.NewBuiltin("examine_scenery", b_examineScenery),

		// Movement.
		"walk_to": starlark.NewBuiltin("walk_to", b_walkTo),

		// Combat / interaction.
		"attack_npc":             starlark.NewBuiltin("attack_npc", b_attackNpc),
		"attack_player":          starlark.NewBuiltin("attack_player", b_attackPlayer),
		"talk_to":                starlark.NewBuiltin("talk_to", b_talkTo),
		"choose_dialog":          starlark.NewBuiltin("choose_dialog", b_chooseDialog),
		"interact_with_boundary": starlark.NewBuiltin("interact_with_boundary", b_interactWithBoundary),
		"pick_up":                starlark.NewBuiltin("pick_up", b_pickUp),
		"drop_item":              starlark.NewBuiltin("drop_item", b_dropItem),
		"item_command":           starlark.NewBuiltin("item_command", b_itemCommand),

		// Social.
		"say":        starlark.NewBuiltin("say", b_say),
		"pm":         starlark.NewBuiltin("pm", b_pm),
		"add_friend": starlark.NewBuiltin("add_friend", b_addFriend),

		// Bank.
		"bank_deposit": starlark.NewBuiltin("bank_deposit", b_bankDeposit),
		"bank_close":   starlark.NewBuiltin("bank_close", b_bankClose),

		// Reactors.
		"combat_loop": starlark.NewBuiltin("combat_loop", b_combatLoop),

		// Utility.
		"sleep":    starlark.NewBuiltin("sleep", b_sleep),
		"command":  starlark.NewBuiltin("command", b_command),
		"position": starlark.NewBuiltin("position", b_position),
		"hp":       starlark.NewBuiltin("hp", b_hp),
	}
}

// hostFromThread fetches the Host stashed by RunString.
func hostFromThread(t *starlark.Thread) *runtime.Host {
	v := t.Local("host")
	if v == nil {
		return nil
	}
	return v.(*runtime.Host)
}

func ctxFromThread(t *starlark.Thread) context.Context {
	v := t.Local("ctx")
	if v == nil {
		return context.Background()
	}
	return v.(context.Context)
}

// ----- Perception builtins -----

func b_lookAround(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var radius starlark.Int = starlark.MakeInt(8)
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "radius?", &radius); err != nil {
		return nil, err
	}
	r, _ := radius.Int64()
	h := hostFromThread(t)
	return starlark.String(h.DescribeSurroundings(int(r))), nil
}

func b_selfState(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	h := hostFromThread(t)
	ex := h.ExamineSelf()
	d := starlark.NewDict(6)
	d.SetKey(starlark.String("x"), starlark.MakeInt(ex.X))
	d.SetKey(starlark.String("y"), starlark.MakeInt(ex.Y))
	d.SetKey(starlark.String("name"), starlark.String(ex.Name))
	d.SetKey(starlark.String("detail"), starlark.String(ex.Detail))
	d.SetKey(starlark.String("hp"), starlark.MakeInt(h.World().Self.HP()))
	d.SetKey(starlark.String("max_hp"), starlark.MakeInt(h.World().Self.MaxHP()))
	return d, nil
}

func b_nearbyNpcs(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	h := hostFromThread(t)
	npcs := h.World().Npcs.All()
	list := starlark.NewList(nil)
	for _, n := range npcs {
		ex := h.ExamineNpc(n.Index)
		d := starlark.NewDict(6)
		d.SetKey(starlark.String("index"), starlark.MakeInt(n.Index))
		d.SetKey(starlark.String("type_id"), starlark.MakeInt(n.TypeID))
		d.SetKey(starlark.String("name"), starlark.String(ex.Name))
		d.SetKey(starlark.String("x"), starlark.MakeInt(n.X))
		d.SetKey(starlark.String("y"), starlark.MakeInt(n.Y))
		d.SetKey(starlark.String("description"), starlark.String(ex.Description))
		// attackable?
		if def := h.Facts().NpcDef(n.TypeID); def != nil {
			d.SetKey(starlark.String("attackable"), starlark.Bool(def.Attackable))
		} else {
			d.SetKey(starlark.String("attackable"), starlark.False)
		}
		list.Append(d)
	}
	return list, nil
}

func b_nearbyPlayers(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	h := hostFromThread(t)
	ps := h.World().Players.All()
	list := starlark.NewList(nil)
	for _, p := range ps {
		d := starlark.NewDict(4)
		d.SetKey(starlark.String("index"), starlark.MakeInt(p.Index))
		d.SetKey(starlark.String("name"), starlark.String(p.Name))
		d.SetKey(starlark.String("x"), starlark.MakeInt(p.X))
		d.SetKey(starlark.String("y"), starlark.MakeInt(p.Y))
		list.Append(d)
	}
	return list, nil
}

func b_groundItems(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	h := hostFromThread(t)
	gi := h.World().GroundItems.All()
	list := starlark.NewList(nil)
	for _, g := range gi {
		ex := h.ExamineItem(g.ItemID)
		d := starlark.NewDict(4)
		d.SetKey(starlark.String("item_id"), starlark.MakeInt(g.ItemID))
		d.SetKey(starlark.String("name"), starlark.String(ex.Name))
		d.SetKey(starlark.String("x"), starlark.MakeInt(g.X))
		d.SetKey(starlark.String("y"), starlark.MakeInt(g.Y))
		list.Append(d)
	}
	return list, nil
}

func b_inventory(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	h := hostFromThread(t)
	slots := h.World().Inventory.Slots()
	list := starlark.NewList(nil)
	for i, s := range slots {
		if s.ItemID == 0 {
			continue
		}
		ex := h.ExamineItem(s.ItemID)
		d := starlark.NewDict(5)
		d.SetKey(starlark.String("slot"), starlark.MakeInt(i))
		d.SetKey(starlark.String("item_id"), starlark.MakeInt(s.ItemID))
		d.SetKey(starlark.String("name"), starlark.String(ex.Name))
		d.SetKey(starlark.String("amount"), starlark.MakeInt(s.Amount))
		d.SetKey(starlark.String("wielded"), starlark.Bool(s.Wielded))
		list.Append(d)
	}
	return list, nil
}

func b_examineNpc(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var idx int
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "index", &idx); err != nil {
		return nil, err
	}
	return starlark.String(hostFromThread(t).ExamineNpc(idx).String()), nil
}

func b_examineItem(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var id int
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "item_id", &id); err != nil {
		return nil, err
	}
	return starlark.String(hostFromThread(t).ExamineItem(id).String()), nil
}

func b_examineScenery(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var x, y int
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "x", &x, "y", &y); err != nil {
		return nil, err
	}
	return starlark.String(hostFromThread(t).ExamineScenery(x, y).String()), nil
}

// ----- Movement -----

func b_walkTo(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var x, y int
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "x", &x, "y", &y); err != nil {
		return nil, err
	}
	if err := hostFromThread(t).WalkTo(ctxFromThread(t), x, y); err != nil {
		return nil, fmt.Errorf("walk_to: %w", err)
	}
	return starlark.None, nil
}

// ----- Combat / interaction -----

func b_attackNpc(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var idx int
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "index", &idx); err != nil {
		return nil, err
	}
	if err := hostFromThread(t).AttackNpc(ctxFromThread(t), idx); err != nil {
		return nil, fmt.Errorf("attack_npc: %w", err)
	}
	return starlark.None, nil
}

func b_attackPlayer(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var idx int
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "index", &idx); err != nil {
		return nil, err
	}
	if err := hostFromThread(t).AttackPlayer(ctxFromThread(t), idx); err != nil {
		return nil, fmt.Errorf("attack_player: %w", err)
	}
	return starlark.None, nil
}

func b_talkTo(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var idx int
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "index", &idx); err != nil {
		return nil, err
	}
	if err := hostFromThread(t).TalkToNpc(ctxFromThread(t), idx); err != nil {
		return nil, fmt.Errorf("talk_to: %w", err)
	}
	return starlark.None, nil
}

func b_chooseDialog(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var option int
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "option", &option); err != nil {
		return nil, err
	}
	if err := hostFromThread(t).ChooseDialogOption(ctxFromThread(t), option); err != nil {
		return nil, fmt.Errorf("choose_dialog: %w", err)
	}
	return starlark.None, nil
}

func b_interactWithBoundary(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var x, y, dir int
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "x", &x, "y", &y, "direction", &dir); err != nil {
		return nil, err
	}
	if err := hostFromThread(t).InteractWithBoundary(ctxFromThread(t), x, y, dir); err != nil {
		return nil, fmt.Errorf("interact_with_boundary: %w", err)
	}
	return starlark.None, nil
}

func b_pickUp(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var x, y, itemID int
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "x", &x, "y", &y, "item_id", &itemID); err != nil {
		return nil, err
	}
	if err := hostFromThread(t).PickUpItem(ctxFromThread(t), x, y, itemID); err != nil {
		return nil, fmt.Errorf("pick_up: %w", err)
	}
	return starlark.None, nil
}

func b_dropItem(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var slot int
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "slot", &slot); err != nil {
		return nil, err
	}
	if err := hostFromThread(t).DropItem(ctxFromThread(t), slot); err != nil {
		return nil, fmt.Errorf("drop_item: %w", err)
	}
	return starlark.None, nil
}

func b_itemCommand(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var slot int
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "slot", &slot); err != nil {
		return nil, err
	}
	if err := hostFromThread(t).ItemCommand(ctxFromThread(t), slot); err != nil {
		return nil, fmt.Errorf("item_command: %w", err)
	}
	return starlark.None, nil
}

// ----- Social -----

func b_say(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var msg string
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "message", &msg); err != nil {
		return nil, err
	}
	if err := hostFromThread(t).Say(ctxFromThread(t), msg); err != nil {
		return nil, fmt.Errorf("say: %w", err)
	}
	return starlark.None, nil
}

func b_pm(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var to, msg string
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "to", &to, "message", &msg); err != nil {
		return nil, err
	}
	if err := hostFromThread(t).PrivateMessage(ctxFromThread(t), to, msg); err != nil {
		return nil, fmt.Errorf("pm: %w", err)
	}
	return starlark.None, nil
}

func b_addFriend(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var name string
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "name", &name); err != nil {
		return nil, err
	}
	if err := hostFromThread(t).AddFriend(ctxFromThread(t), name); err != nil {
		return nil, fmt.Errorf("add_friend: %w", err)
	}
	return starlark.None, nil
}

// ----- Bank -----

func b_bankDeposit(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var itemID, amount int
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "item_id", &itemID, "amount", &amount); err != nil {
		return nil, err
	}
	if err := hostFromThread(t).BankDeposit(ctxFromThread(t), itemID, amount); err != nil {
		return nil, fmt.Errorf("bank_deposit: %w", err)
	}
	return starlark.None, nil
}

func b_bankClose(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	if err := hostFromThread(t).BankClose(ctxFromThread(t)); err != nil {
		return nil, fmt.Errorf("bank_close: %w", err)
	}
	return starlark.None, nil
}

// ----- Reactors -----

func b_combatLoop(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var target string
	var kills int = 5
	var hpThreshold float64 = 0.4
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "target", &target, "kills?", &kills, "auto_eat_below?", &hpThreshold); err != nil {
		return nil, err
	}
	h := hostFromThread(t)
	opts := runtime.DefaultCombatLoopOptions()
	opts.MaxKills = kills
	opts.AutoEatHPFraction = hpThreshold
	// Resolve target by name.
	opts.TargetTypeIDs = nil
	for id, def := range h.Facts().NpcDefs {
		if def != nil && def.Attackable && (def.Name == target || containsFold(def.Name, target)) {
			opts.TargetTypeIDs = append(opts.TargetTypeIDs, id)
		}
	}
	if len(opts.TargetTypeIDs) == 0 {
		return nil, fmt.Errorf("combat_loop: no attackable NPC matches %q", target)
	}
	if err := h.CombatLoop(ctxFromThread(t), opts); err != nil {
		return nil, fmt.Errorf("combat_loop: %w", err)
	}
	return starlark.None, nil
}

// ----- Utility -----

func b_sleep(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var secs float64
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "seconds", &secs); err != nil {
		return nil, err
	}
	d := time.Duration(secs * float64(time.Second))
	select {
	case <-ctxFromThread(t).Done():
		return nil, ctxFromThread(t).Err()
	case <-time.After(d):
	}
	return starlark.None, nil
}

func b_command(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	var cmd string
	if err := starlark.UnpackArgs(fn.Name(), args, kwargs, "command", &cmd); err != nil {
		return nil, err
	}
	if err := hostFromThread(t).Command(ctxFromThread(t), cmd); err != nil {
		return nil, fmt.Errorf("command: %w", err)
	}
	return starlark.None, nil
}

func b_position(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	pos := hostFromThread(t).World().Self.Position()
	tup := starlark.Tuple{starlark.MakeInt(pos.X), starlark.MakeInt(pos.Y)}
	return tup, nil
}

func b_hp(t *starlark.Thread, fn *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	h := hostFromThread(t)
	tup := starlark.Tuple{starlark.MakeInt(h.World().Self.HP()), starlark.MakeInt(h.World().Self.MaxHP())}
	return tup, nil
}

// containsFold is a tiny case-insensitive substring check we use to
// match NPC type names (e.g., "goblin" matches "Goblin" and
// "Lesser Demon Goblin").
func containsFold(haystack, needle string) bool {
	if len(needle) == 0 {
		return true
	}
	if len(needle) > len(haystack) {
		return false
	}
	for i := 0; i+len(needle) <= len(haystack); i++ {
		if eqFold(haystack[i:i+len(needle)], needle) {
			return true
		}
	}
	return false
}

func eqFold(a, b string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := 0; i < len(a); i++ {
		ca, cb := a[i], b[i]
		if ca >= 'A' && ca <= 'Z' {
			ca += 32
		}
		if cb >= 'A' && cb <= 'Z' {
			cb += 32
		}
		if ca != cb {
			return false
		}
	}
	return true
}

// Compile-time check that imports are used.
var _ = action.PrivateMessage
var _ = world.Coord{}
