package v235

import (
	"crypto/rand"
	"encoding/binary"
	"fmt"
)

// LoginPayload encodes the OpenRSC v235 client→server login packet's
// payload body (the bytes that appear AFTER the framing length and
// opcode, before the framing wraps it). Use EncodeLoginFrame for the
// complete on-wire bytes.
//
// Per OpenRSC's net/rsc/LoginPacketHandler.java:103-200 (clientVersion >
// 204 path), the payload layout is:
//
//	[1 byte]  info        — 0 = new login, 1 = reconnect
//	[1 byte]  info2       — 0 for modern clients
//	[1 byte]  info3       — high 8 bits of clientVersion if > 65536, else 0
//	[2 bytes] versionLow  — clientVersion as a big-endian unsigned short
//	[2 bytes] rsaLength   — length of the RSA-encrypted block that follows
//	[rsaLength bytes]     — RSA-encrypted credential block
//	[2 bytes] xteaLength  — length of the XTEA-encrypted block
//	[xteaLength bytes]    — XTEA-encrypted username block
//
// Both encrypted blocks are described in BuildRSABlock and BuildXTEABlock.
type LoginPayload struct {
	Username      string
	Password      string
	ClientVersion uint16 // 235 for the Payload235 target

	// IsaacKeys are the 4 uint32s the client commits to as the ISAAC
	// seed. The server extracts these from the decrypted RSA block.
	// If zero, they will be generated by Encode().
	IsaacKeys [4]uint32

	// Nonces are 12 random uint32s used as session nonces. Indices 0-4
	// go in the RSA block (plus a partial 24-bit nonce[5]); indices
	// 6-11 go in the XTEA block. If zero, they will be generated.
	Nonces [12]uint32
}

// EncodeLoginFrame returns the complete on-wire bytes for the login
// packet, including the framing (length byte/bytes + tail-byte
// reordering + opcode + payload). The opcode is sent plain because
// ISAAC is not yet seeded.
func (p *LoginPayload) EncodeLoginFrame(pub *RSAPublicKey) ([]byte, error) {
	body, err := p.encodePayload(pub)
	if err != nil {
		return nil, err
	}
	return EncodeFrame(OutLogin, body), nil
}

// encodePayload builds the payload body for the login packet (without
// framing). Exposed for testing.
func (p *LoginPayload) encodePayload(pub *RSAPublicKey) ([]byte, error) {
	// Fill defaults for unset keys/nonces.
	if isZeroKeys(p.IsaacKeys) {
		if err := randomKeys(&p.IsaacKeys); err != nil {
			return nil, err
		}
	}
	if isZeroNonces(p.Nonces) {
		if err := randomNonces(&p.Nonces); err != nil {
			return nil, err
		}
	}

	rsaBlock, err := BuildRSABlock(p.Password, p.IsaacKeys, p.Nonces)
	if err != nil {
		return nil, err
	}
	rsaCiphertext, err := pub.Encrypt(rsaBlock)
	if err != nil {
		return nil, fmt.Errorf("rsa encrypt: %w", err)
	}

	xteaBlock, err := BuildXTEABlock(p.Username, p.Nonces)
	if err != nil {
		return nil, err
	}
	// Encrypt the XTEA block in place with the same 4 keys.
	if err := XTEAEncrypt(xteaBlock, p.IsaacKeys); err != nil {
		return nil, fmt.Errorf("xtea encrypt: %w", err)
	}

	// Now lay out the payload body.
	body := NewBuffer(8 + len(rsaCiphertext) + len(xteaBlock))
	body.WriteByte(0)                 // info: new login
	body.WriteByte(0)                 // info2
	body.WriteByte(0)                 // info3
	body.WriteUint16(p.ClientVersion) // version short
	body.WriteUint16(uint16(len(rsaCiphertext)))
	body.WriteBytes(rsaCiphertext)
	body.WriteUint16(uint16(len(xteaBlock)))
	body.WriteBytes(xteaBlock)
	return body.Bytes(), nil
}

// BuildRSABlock constructs the 61-byte RSA plaintext block per
// LoginPacketHandler.java:152-173. Layout:
//
//	byte 0      — checksum, always 10 (authentic client signature)
//	bytes 1-16  — 4 uint32s big-endian: ISAAC/XTEA keys
//	bytes 17-36 — 20 bytes: password, UTF-8, space-padded, spaces→underscores
//	byte 37     — unused (filled with random)
//	bytes 38-57 — 5 uint32s big-endian: nonces[0..4]
//	bytes 58-60 — 3 bytes: nonces[5] low 24 bits
func BuildRSABlock(password string, keys [4]uint32, nonces [12]uint32) ([]byte, error) {
	block := make([]byte, 61)
	block[0] = 10
	for i, k := range keys {
		binary.BigEndian.PutUint32(block[1+i*4:], k)
	}

	pwBytes := encodePassword(password)
	copy(block[17:37], pwBytes)

	// byte 37 left at random; we set it to a fixed pad to keep deterministic
	// behaviour easier to debug. The server doesn't read this byte.
	block[37] = 0xFF

	for i := 0; i < 5; i++ {
		binary.BigEndian.PutUint32(block[38+i*4:], nonces[i])
	}
	// nonces[5] only uses 24 bits — write the low 3 bytes.
	n5 := nonces[5]
	block[58] = byte(n5 >> 16)
	block[59] = byte(n5 >> 8)
	block[60] = byte(n5)
	return block, nil
}

// BuildXTEABlock constructs the XTEA plaintext block per
// LoginPacketHandler.java:178-192. Layout:
//
//	byte 0        — limit30 (semantic unclear; we send 0x1E = 30)
//	bytes 1-24    — 6 uint32s big-endian: nonces[6..11]
//	bytes 25..    — username (UTF-8), null-padded to next 8-byte boundary
//
// The block length is rounded up to a multiple of 8 because XTEA
// operates on 64-bit blocks.
func BuildXTEABlock(username string, nonces [12]uint32) ([]byte, error) {
	usrBytes := []byte(username)
	const fixed = 1 + 24 // limit30 + 6 nonces
	total := fixed + len(usrBytes)
	// pad to multiple of 8
	if rem := total % 8; rem != 0 {
		total += 8 - rem
	}
	block := make([]byte, total)
	block[0] = 30
	for i := 0; i < 6; i++ {
		binary.BigEndian.PutUint32(block[1+i*4:], nonces[6+i])
	}
	copy(block[25:], usrBytes)
	// Remaining bytes are already zero from make.
	return block, nil
}

// encodePassword returns 20 bytes representing the password, with
// spaces converted to underscores (per LoginPacketHandler.java:163
// comment) and right-space-padded to 20 bytes. Per the server, the
// resulting string is trimmed before bcrypt-checking.
func encodePassword(pw string) []byte {
	// Convert spaces → underscores (matches authentic-client behavior).
	tr := make([]byte, 0, 20)
	for _, r := range pw {
		if r == ' ' {
			tr = append(tr, '_')
		} else {
			tr = append(tr, byte(r))
		}
		if len(tr) >= 20 {
			break
		}
	}
	for len(tr) < 20 {
		tr = append(tr, ' ')
	}
	return tr[:20]
}

// ----- helpers -----

func isZeroKeys(k [4]uint32) bool {
	return k[0] == 0 && k[1] == 0 && k[2] == 0 && k[3] == 0
}

func isZeroNonces(n [12]uint32) bool {
	for _, v := range n {
		if v != 0 {
			return false
		}
	}
	return true
}

func randomKeys(out *[4]uint32) error {
	var buf [16]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return err
	}
	for i := 0; i < 4; i++ {
		out[i] = binary.BigEndian.Uint32(buf[i*4:])
	}
	return nil
}

func randomNonces(out *[12]uint32) error {
	var buf [48]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return err
	}
	for i := 0; i < 12; i++ {
		out[i] = binary.BigEndian.Uint32(buf[i*4:])
	}
	return nil
}
